/**
 * Equations harvested from the 72 reference models in
 * `Simile reference/Simile_XSugar/Models_SimileProlog/`, which are outside this
 * repository — hence the copy. This is the evidence behind the grammar: every
 * departure from the 2007 XSugar grammar, and every construct no document
 * describes (`&&`, bare `!`, unbracketed `not`, the quoted `'!='`), was found
 * by running the parser over these and reading the failures.
 *
 * Rows are [model, equation] — or [model, equation, 1] for a KNOWN EXCLUSION,
 * meaning it is expected not to parse. All 12 of those are the Prolog
 * spellings of the boolean operators, `(a,b,c)` for and and `(a;b;c)` for or,
 * deliberately dropped (ruled 2026-08-06) because they collide with argument
 * separators. Reinstating them is a small change to the grammar, not to this.
 *
 * 1500 distinct (model, equation) pairs, from 1678 occurrences.
 * Generated, but committed and edited by hand thereafter if need be — the
 * models it came from are not in this repository, so it cannot be regenerated
 * from a clean checkout.
 *
 * Classic script, loaded by test/index.html.
 */
window.Sienna = window.Sienna || {};
window.Sienna.equationCorpus = [
  ["ageclass4.pl", " 0.01"],
  ["ageclass4.pl", " 0.05"],
  ["ageclass4.pl", " 0.05 *(1-pop_size/100)"],
  ["ageclass4.pl", " 0.1 *(1-pop_size/100)"],
  ["ageclass4.pl", " 0.1 *pop_size_3"],
  ["ageclass4.pl", " 0.2 *(1-pop_size/100)"],
  ["ageclass4.pl", " 0.2 *pop_size_2"],
  ["ageclass4.pl", "0"],
  ["ageclass4.pl", "2"],
  ["ageclass4.pl", "births_2+births_3+births_4"],
  ["ageclass4.pl", "m1*pop_size_1"],
  ["ageclass4.pl", "m2*pop_size_2"],
  ["ageclass4.pl", "m3*pop_size_3"],
  ["ageclass4.pl", "m4*pop_size_4"],
  ["ageclass4.pl", "pop_size_1"],
  ["ageclass4.pl", "pop_size_1+pop_size_2+pop_size_3+pop_size_4"],
  ["ageclass4.pl", "r2*pop_size_2"],
  ["ageclass4.pl", "r3*pop_size_3"],
  ["ageclass4.pl", "r4*pop_size_4"],
  ["ageclass5.pl", "(if index(1)==1 then births else 0)"],
  ["ageclass5.pl", "(if index(1)>1 then element([ageing],index(1)-1) else 0)"],
  ["ageclass5.pl", "[ageing_out]"],
  ["ageclass5.pl", "element([ 0.05, 0.01, 0.01, 0.05],index(1))"],
  ["ageclass5.pl", "element([0, 0.05, 0.2, 0.1],index(1))*(1-pop_size/100)"],
  ["ageclass5.pl", "element([1, 0.2, 0.1,0],index(1))*pop_size"],
  ["ageclass5.pl", "element([2,0,0,0],index(1))"],
  ["ageclass5.pl", "m*pop_size"],
  ["ageclass5.pl", "r*pop_size"],
  ["ageclass5.pl", "sum([pop_size])"],
  ["ageclass5.pl", "sum([these_births])"],
  ["ageclass6.pl", "(class_next==class_this+1)"],
  ["ageclass6.pl", "(if index(1)==1 then births else 0)"],
  ["ageclass6.pl", "ageing_out_this"],
  ["ageclass6.pl", "element([ 0.05, 0.01, 0.01, 0.05],index(1))"],
  ["ageclass6.pl", "element([0, 0.05, 0.2, 0.1],index(1))*(1-total_pop_size/100)"],
  ["ageclass6.pl", "element([1, 0.2, 0.1,0],index(1))*pop_size"],
  ["ageclass6.pl", "element([2,0,0,0],index(1))"],
  ["ageclass6.pl", "index(1)"],
  ["ageclass6.pl", "m*pop_size"],
  ["ageclass6.pl", "r*pop_size"],
  ["ageclass6.pl", "sum([pop_size])"],
  ["ageclass6.pl", "sum([these_births])"],
  ["ageclass6.pl", "sum({ageing_next})"],
  ["animal1.pl", " 0.6"],
  ["animal1.pl", "(if (x<0;x>100;y<0;y>100) then 1 else 0)", 1],
  ["animal1.pl", "(if outside==1 then  3.14/dt(1) else rand( -0.4, 0.4)/dt(1))"],
  ["animal1.pl", "(if outside==1 then speed*cos(dir+ 3.14) else speed*cos(dir))"],
  ["animal1.pl", "(if outside==1 then speed*sin(dir+ 3.14) else speed*sin(dir))"],
  ["animal1.pl", "1"],
  ["animal1.pl", "100"],
  ["animal1.pl", "3"],
  ["animal1.pl", "5"],
  ["animal1.pl", "rand(0, 6.28)"],
  ["animal1.pl", "rand(0,2* 0.7)"],
  ["animal1.pl", "rand(30,70)"],
  ["animal1.pl", "sum({one})"],
  ["AntsWorld.pl", " -a-b"],
  ["AntsWorld.pl", " 0.1"],
  ["AntsWorld.pl", "'Pheromone_output_at'"],
  ["AntsWorld.pl", "(if all([a,b,c]> - (n/2)) and all([a,b,c]<n/2) then n*a+b+ceil(n*n/2) else 0)"],
  ["AntsWorld.pl", "(index(1) is my_space_at)"],
  ["AntsWorld.pl", "(infront=element(last([neighbour_spaces]),my_direction),if time('')==init_time('') then 5102 elseif infront>0 then infront else prev(1))"],
  ["AntsWorld.pl", "(off=sqrt(3/4),x+element([0,off,off,0,-off,-off],index(1)))"],
  ["AntsWorld.pl", "[-1,-1,0,1,1,0]"],
  ["AntsWorld.pl", "[0,1,1,0,-1,-1]"],
  ["AntsWorld.pl", "[1,0,-1,-1,0,1]"],
  ["AntsWorld.pl", "[neighbours_at]"],
  ["AntsWorld.pl", "[their_ids_has]"],
  ["AntsWorld.pl", "0"],
  ["AntsWorld.pl", "1"],
  ["AntsWorld.pl", "2"],
  ["AntsWorld.pl", "50+(a-c)* 0.866"],
  ["AntsWorld.pl", "50+b* 1.5"],
  ["AntsWorld.pl", "a+element([neighbour_offsets_a],index(1))"],
  ["AntsWorld.pl", "b+element([neighbour_offsets_b],index(1))"],
  ["AntsWorld.pl", "c+element([neighbour_offsets_c],index(1))"],
  ["AntsWorld.pl", "ceil(index(1)/n)-ceil(n/2)"],
  ["AntsWorld.pl", "ceil(rand_var(0,6))"],
  ["AntsWorld.pl", "index(1)"],
  ["AntsWorld.pl", "index(1)-n*a-ceil(n*n/2)"],
  ["AntsWorld.pl", "int(sqrt(size('World')))"],
  ["AntsWorld.pl", "sum({'Pheromone_has'})"],
  ["AntsWorld.pl", "x_at"],
  ["AntsWorld.pl", "x_has"],
  ["AntsWorld.pl", "y_at"],
  ["AntsWorld.pl", "y_has"],
  ["AntsWorld.pl", "y+element([1, 0.5, -0.5,-1, -0.5, 0.5],index(1))"],
  ["ArcieroAggressiveTumorMode.pl", "'E'*'I'/(g1+'I')*(p1-q1*'S'/(q2+'S'))"],
  ["ArcieroAggressiveTumorMode.pl", "0"],
  ["ArcieroAggressiveTumorMode.pl", "1"],
  ["ArcieroAggressiveTumorMode.pl", "c*'T'/(1+gamma*'S')"],
  ["ArcieroAggressiveTumorMode.pl", "min(a*'E'*'T'/(g2+'T'),'T')"],
  ["ArcieroAggressiveTumorMode.pl", "mu1*'E'"],
  ["ArcieroAggressiveTumorMode.pl", "mu2*'I'"],
  ["ArcieroAggressiveTumorMode.pl", "mu3*'S'"],
  ["ArcieroAggressiveTumorMode.pl", "p2*'S'*'T'/(g3+'S')"],
  ["ArcieroAggressiveTumorMode.pl", "p3*'E'*'T'/((g4+'T')*(1+alpha*'S'))"],
  ["ArcieroAggressiveTumorMode.pl", "p4*'T'^2/(tor_c^2+'T'^2)"],
  ["ArcieroAggressiveTumorMode.pl", "r*'T'*(1-'T'/'K')"],
  ["assoc_from_data1.pl", "(any('ID1'==['ID1'] and 'ID2'==['ID2']) or any('ID1'==['ID2'] and 'ID2'==['ID1']))"],
  ["assoc_from_data1.pl", "index(1)"],
  ["assoc_from_data2.pl", "(any('ID1'==['ID1'] and 'ID2'==['ID2']) or any('ID1'==['ID2'] and 'ID2'==['ID1']))"],
  ["assoc_from_data2.pl", "index(1)"],
  ["ballberry1.pl", " 0.01"],
  ["ballberry1.pl", "'A_Q'*last('Gs_0')"],
  ["ballberry1.pl", "'A'"],
  ["ballberry1.pl", "'Gs_0'-last('Gs_0')"],
  ["ballberry1.pl", "(if time('')==0 then g_0 else last('Gs_0'))"],
  ["ballberry1.pl", "(if time('')==time then 'Gs' else g_0+g_1*'A'*'H'/'C_a')"],
  ["ballberry1.pl", "23"],
  ["ballberry1.pl", "graph('Q')"],
  ["ballberry1.pl", "graph(time(''))"],
  ["ballberry1.pl", "last(errorGs_0)"],
  ["ballberry1.pl", "time('')"],
  ["BallBerry4aP.pl", " 0.01"],
  ["BallBerry4aP.pl", "'A_Q'*'Gs'"],
  ["BallBerry4aP.pl", "(abs('Gs'-'Gs_0')< 0.001)"],
  ["BallBerry4aP.pl", "(if loop_count==0 then 'Gs_start' else 'Gs_0')"],
  ["BallBerry4aP.pl", "(if time('')==0 then g_0 else last('Gs_0'))"],
  ["BallBerry4aP.pl", "23"],
  ["BallBerry4aP.pl", "g_0+g_1*'A'*'H'/'C_a'"],
  ["BallBerry4aP.pl", "graph('Q')"],
  ["BallBerry4aP.pl", "graph(time(''))"],
  ["BallBerry4aP.pl", "iterations(al1)"],
  ["besn1.pl", " 0.01 *soil"],
  ["besn1.pl", " 0.01 *wood"],
  ["besn1.pl", " 0.5 *canopy"],
  ["besn1.pl", " 0.5 *soil"],
  ["besn1.pl", " 0.9 *canopy"],
  ["besn1.pl", " 0.9 *litter"],
  ["besn1.pl", "0"],
  ["besn1.pl", "50"],
  ["biome1.pl", " 0.08"],
  ["biome1.pl", " 0.1"],
  ["biome1.pl", " 0.5"],
  ["biome1.pl", "(1-alpha/td)^ 0.5"],
  ["biome1.pl", "(1-z)*w2/(z*w1+(1-z)*w2)"],
  ["biome1.pl", "(if temp<13 then  0.07 else (if temp>38 then  0.04 else  0.04+ 0.03 *(temp-13)/(38-13)))"],
  ["biome1.pl", "(if temp<5 then 0 else (if temp>35 then 0 else (if temp<20 then (temp-5)/(20-5) else (if temp>30 then (temp-30)/(35-30) else 1))))"],
  ["biome1.pl", "1"],
  ["biome1.pl", "1-sum([f])"],
  ["biome1.pl", "100"],
  ["biome1.pl", "15"],
  ["biome1.pl", "1500"],
  ["biome1.pl", "20"],
  ["biome1.pl", "20*bare"],
  ["biome1.pl", "200"],
  ["biome1.pl", "300"],
  ["biome1.pl", "40"],
  ["biome1.pl", "500"],
  ["biome1.pl", "aa- 0.4 *ap"],
  ["biome1.pl", "alpha*f*e"],
  ["biome1.pl", "ap*phi_d*phi_t"],
  ["biome1.pl", "beta*f*e"],
  ["biome1.pl", "c*wr"],
  ["biome1.pl", "e/d"],
  ["biome1.pl", "element([ 0.33, 0.33, 0.9, 0.9],index(1))"],
  ["biome1.pl", "element([1,0,0,0],index(1))"],
  ["biome1.pl", "fmod(time(1),12)"],
  ["biome1.pl", "fpar*sigma*phi*im"],
  ["biome1.pl", "graph(month)"],
  ["biome1.pl", "min(s,d)"],
  ["biome1.pl", "sum([transp1])"],
  ["biome1.pl", "sum([transp2])"],
  ["biome1.pl", "transp+transp2"],
  ["biome1.pl", "water*thetamax1*d1/(d1+d2)"],
  ["biome1.pl", "water*thetamax2*d2/(d1+d2)"],
  ["biome1.pl", "z*w1/(z*w1+(1-z)*w2)"],
  ["biome1.pl", "z*w1+(1-z)*w2"],
  ["biomewater2.pl", " 0.1"],
  ["biomewater2.pl", "100"],
  ["biomewater2.pl", "15"],
  ["biomewater2.pl", "1500"],
  ["biomewater2.pl", "20"],
  ["biomewater2.pl", "20*bare"],
  ["biomewater2.pl", "200"],
  ["biomewater2.pl", "300"],
  ["biomewater2.pl", "40"],
  ["biomewater2.pl", "500"],
  ["biomewater2.pl", "transp+transp2"],
  ["biomewater2.pl", "water*thetamax1*d1/(d1+d2)"],
  ["biomewater2.pl", "water*thetamax2*d2/(d1+d2)"],
  ["broomgrass1.pl", " 0.5"],
  ["broomgrass1.pl", " 0.99 *total_harvesting"],
  ["broomgrass1.pl", "(1==0)"],
  ["broomgrass1.pl", "(if alternative_income_sources then 0 elseif permit_price<expected_income_before_harvesting then number_of_permits else number_of_people_not_farming)"],
  ["broomgrass1.pl", "(if burning_internsity==2 then 'Broom_Grass__in_Machije_Vlei' else agriculture+decomposition+element([proportion_of_grass_by__digging_uprooting__or_cutting],1)*total_harvesting/300)"],
  ["broomgrass1.pl", "(if element([time_of_harvesting],1)==6 and burning_internsity==1 and season==6 then produce else 0)"],
  ["broomgrass1.pl", "(if element([time_of_harvesting],1)==6 then 1 else 0)"],
  ["broomgrass1.pl", "(if frequency_of_burning*burning_internsity>0 and element([proportion_of_grass_by__digging_uprooting__or_cutting],3)>0 then grass_growth*'Broom_Grass__in_Machije_Vlei'+germination else 0)"],
  ["broomgrass1.pl", "(if rainfall>100 then 1 else 0)"],
  ["broomgrass1.pl", "(if rules_enforcement> 0.5 then [5,10,85] else [80,10,10])"],
  ["broomgrass1.pl", "(if rules_enforcement> 0.5 then [set_harvesting_season] elseif number_of_people_not_farming>0 then [set_harvesting_season]-3 else [set_harvesting_season])"],
  ["broomgrass1.pl", "(if rules_enforcement> 0.5 then 0 elseif season>=6 and season<10 then burning_events else 0)"],
  ["broomgrass1.pl", "(if season>=6 and season<=10 and frequency_of_burning>0 then 2 else 1)"],
  ["broomgrass1.pl", "(if soil_moisture==1 then seeds else 0)"],
  ["broomgrass1.pl", "(if transport_cost<=10 then 1 else 0)"],
  ["broomgrass1.pl", "(if'Broom_Grass__in_Machije_Vlei'==0 then 0 elseif harvest then (element([proportion_of_grass_by__digging_uprooting__or_cutting],1)+element([proportion_of_grass_by__digging_uprooting__or_cutting],2))* 0.008 *number_of_harvesters*quantity_harvested_per_person+element([proportion_of_grass_by__digging_uprooting__or_cutting],3)* 0.012 *number_of_harvesters*quantity_harvested_per_person else 0)"],
  ["broomgrass1.pl", "[193,185,70,32,7,2,0,0,4,28,91,128]"],
  ["broomgrass1.pl", "[6,7,8,9,10]"],
  ["broomgrass1.pl", "1"],
  ["broomgrass1.pl", "1-growth_rate*soil_moisture/'K'"],
  ["broomgrass1.pl", "10"],
  ["broomgrass1.pl", "100"],
  ["broomgrass1.pl", "1000000"],
  ["broomgrass1.pl", "150"],
  ["broomgrass1.pl", "2"],
  ["broomgrass1.pl", "3+last(quality_of_broom)*season/(supply_from_other_sources+1)"],
  ["broomgrass1.pl", "30"],
  ["broomgrass1.pl", "300"],
  ["broomgrass1.pl", "5"],
  ["broomgrass1.pl", "75000"],
  ["broomgrass1.pl", "any([time_of_harvesting]==season)"],
  ["broomgrass1.pl", "availability_of_transport*number_of_brooms_made"],
  ["broomgrass1.pl", "beauty*life_of_broom*comfort"],
  ["broomgrass1.pl", "bundling_with_tube_or_fibre*ripe_or_unripe*length*whether_cut__or_dug_or_uprooted"],
  ["broomgrass1.pl", "element([proportion_of_grass_by__digging_uprooting__or_cutting],3)/100"],
  ["broomgrass1.pl", "element([rainfall_this_month],season)"],
  ["broomgrass1.pl", "fmod(time(1),12)+1"],
  ["broomgrass1.pl", "length"],
  ["broomgrass1.pl", "market_price_per_broom"],
  ["broomgrass1.pl", "market_price_per_broom*2000-permit_price-availability_of_transport"],
  ["broomgrass1.pl", "maximum_number_of_broom__harvest_per_day"],
  ["broomgrass1.pl", "number_of_brooms_made*market_price_per_broom-permit_price-transport_cost"],
  ["broomgrass1.pl", "number_of_brooms_sold*market_price_per_broom-permit_price"],
  ["broomgrass1.pl", "processing+bundling_with_tube_or_fibre"],
  ["budworm1.pl", "(if budworm>300 then forest-1 else 0)"],
  ["budworm1.pl", "(if forest<4 then  0.02 else 0)"],
  ["budworm1.pl", "1"],
  ["budworm1.pl", "10"],
  ["budworm1.pl", "budworm"],
  ["budworm1.pl", "forest*graph(budworm)*budworm"],
  ["century_gc_daily.pl", " 0.0117"],
  ["century_gc_daily.pl", " 0.03"],
  ["century_gc_daily.pl", " 0.2"],
  ["century_gc_daily.pl", " 0.42"],
  ["century_gc_daily.pl", " 0.45"],
  ["century_gc_daily.pl", " 0.52"],
  ["century_gc_daily.pl", " 0.7"],
  ["century_gc_daily.pl", " 0.85 - 0.018 *'Lignin'/'Nitrogen'"],
  ["century_gc_daily.pl", " 0.85 - 0.68 *'Clay'"],
  ["century_gc_daily.pl", "'Active_Soil_C'*ka* 0.004"],
  ["century_gc_daily.pl", "'Active_Soil_C'*ka*'Respa'"],
  ["century_gc_daily.pl", "'Active_Soil_C'*ka*'UtilEffas'"],
  ["century_gc_daily.pl", "'Active_Soil_C'+'Passive_Soil_C'+'Slow_Soil_C'"],
  ["century_gc_daily.pl", "'Active_Soil_N'+'Passive_Soil_N'+'Slow_Soil_N'"],
  ["century_gc_daily.pl", "'Carbon'/'Nitrogen'"],
  ["century_gc_daily.pl", "'CO2_a'+'CO2s'+'CO2p'"],
  ["century_gc_daily.pl", "'CO2_LiMet'+'CO2_LiSta'+'CO2_LiSts'"],
  ["century_gc_daily.pl", "'DecNa'-'FNma'"],
  ["century_gc_daily.pl", "'DecNsta'-'FNsta'"],
  ["century_gc_daily.pl", "'DecNsts'-'FNsts'"],
  ["century_gc_daily.pl", "'DecompNa'-'FNas'-'FNap'"],
  ["century_gc_daily.pl", "'DecompNp'-'FNpa'"],
  ["century_gc_daily.pl", "'DecompNs'-'FNsa'-'FNsp'"],
  ["century_gc_daily.pl", "'Fap'/'CN_passive_SOM'"],
  ["century_gc_daily.pl", "'Fas'/'CN_slow_SOM'"],
  ["century_gc_daily.pl", "'Fas'/'UtilEffas'/'CN_active_SOM'"],
  ["century_gc_daily.pl", "'Fma'/'CN_active_SOM'"],
  ["century_gc_daily.pl", "'Fma'/'UtilEffm'/'CN_LiMet'"],
  ["century_gc_daily.pl", "'Fpa'/'CN_active_SOM'"],
  ["century_gc_daily.pl", "'Fpa'/'UtilEffp'/'CN_passive_SOM'"],
  ["century_gc_daily.pl", "'Fsa'/'CN_active_SOM'"],
  ["century_gc_daily.pl", "'Fsp'/'CN_passive_SOM'"],
  ["century_gc_daily.pl", "'Fsp'/'UtilEffsp'/'CN_slow_SOM'"],
  ["century_gc_daily.pl", "'Fsta'/'CN_active_SOM'"],
  ["century_gc_daily.pl", "'Fsta'/'UtilEffSta'/'CN_LiSt'"],
  ["century_gc_daily.pl", "'Fsts'/'CN_slow_SOM'"],
  ["century_gc_daily.pl", "'Fsts'/'UtilEffsts'/'CN_LiSt'"],
  ["century_gc_daily.pl", "'INIT_LiMetabolicN'"],
  ["century_gc_daily.pl", "'INIT_Listructural_N'"],
  ["century_gc_daily.pl", "'Initial_C'*'SplitMet'"],
  ["century_gc_daily.pl", "'Initial_C'*'SplitMet'/'CNLiMet'"],
  ["century_gc_daily.pl", "'Initial_C'*(1-'SplitMet')"],
  ["century_gc_daily.pl", "'Initial_C'*(1-'SplitMet')/'CN_LiSt'"],
  ["century_gc_daily.pl", "'Lignin'/(1-'SplitMet')"],
  ["century_gc_daily.pl", "'LiMetabolic_C'*klim*'UtilEffm'"],
  ["century_gc_daily.pl", "'LiMetabolic_C'*klim*(1-'UtilEffm')"],
  ["century_gc_daily.pl", "'LiMetabolic_C'+'LiStructural_C'"],
  ["century_gc_daily.pl", "'LiMetabolic_N'+'LiStructuralN'"],
  ["century_gc_daily.pl", "'LiStructural_C'*'StructLignin'*klist*'UtilEffsts'"],
  ["century_gc_daily.pl", "'LiStructural_C'*'StructLignin'*klist*(1-'UtilEffsts')"],
  ["century_gc_daily.pl", "'LiStructural_C'*(1-'StructLignin')*klist*'UtilEffSta'"],
  ["century_gc_daily.pl", "'LiStructural_C'*(1-'StructLignin')*klist*(1-'UtilEffSta')"],
  ["century_gc_daily.pl", "'Mineral_N'/('Initial_C'/'Carbon'*'Nitrogen')*100"],
  ["century_gc_daily.pl", "'Passive_Soil_C'*kp*'UtilEffp'"],
  ["century_gc_daily.pl", "'Passive_Soil_C'*kp*(1-'UtilEffp')"],
  ["century_gc_daily.pl", "'Slow_Soil_C'*ks*'UtilEffsa'"],
  ["century_gc_daily.pl", "'Slow_Soil_C'*ks*'UtilEffsp'"],
  ["century_gc_daily.pl", "'Slow_Soil_C'*ks*(1-'UtilEffsa'-'UtilEffsp')"],
  ["century_gc_daily.pl", "'Soil_CO2'+'Litter_CO2'"],
  ["century_gc_daily.pl", "'SplitMet'/(1/'Residue_CN'-(1-'SplitMet')/'CN_LiSt')"],
  ["century_gc_daily.pl", "'Temperature'"],
  ["century_gc_daily.pl", "'Total_SOM_N'+'Mineral_N'"],
  ["century_gc_daily.pl", "(if'ArrayPosOfLowerXNW'<1 then 1 else (if'ArrayPosOfLowerXNW'=='ArraySize' then 'ArrayPosOfLowerXNW'-1 else 'ArrayPosOfLowerXNW'))"],
  ["century_gc_daily.pl", "(if'Demandma'>'DecNa' then 'DecNa' else 'Demandma')"],
  ["century_gc_daily.pl", "(if'Demandma'>'DecNa' then 'Demandma'-'DecNa' else 0)"],
  ["century_gc_daily.pl", "(if'Demandsta'>'DecNsta' then 'DecNsta' else 'Demandsta')"],
  ["century_gc_daily.pl", "(if'Demandsta'>'DecNsta' then 'Demandsta'-'DecNsta' else 0)"],
  ["century_gc_daily.pl", "(if'Demandsts'>'DecNsts' then 'DecNsts' else 'Demandsts')"],
  ["century_gc_daily.pl", "(if'Demandsts'>'DecNsts' then 'Demandsts'-'DecNsts' else 0)"],
  ["century_gc_daily.pl", "[ 0.01, 0.05, 0.15, 0.3, 0.5, 0.7, 0.9,1, 0.95,0,0]"],
  ["century_gc_daily.pl", "[0,5,10,15,20,25,30,35,40,45,50]"],
  ["century_gc_daily.pl", "[xtable]"],
  ["century_gc_daily.pl", "[ytable]"],
  ["century_gc_daily.pl", "0"],
  ["century_gc_daily.pl", "1-'Respa'- 0.004"],
  ["century_gc_daily.pl", "1-(1- 0.00013 *'TempMod')^(1/7)"],
  ["century_gc_daily.pl", "1-(1- 0.0038 *'TempMod')^(1/7)"],
  ["century_gc_daily.pl", "1-(1- 0.094 *exp( -3.0*'StructLignin')*'TempMod')^(1/7)"],
  ["century_gc_daily.pl", "1-(1- 0.14 *(1- 0.75 *'Clay')*'TempMod')^(1/7)"],
  ["century_gc_daily.pl", "1-(1- 0.35 *'TempMod')^(1/7)"],
  ["century_gc_daily.pl", "100"],
  ["century_gc_daily.pl", "11"],
  ["century_gc_daily.pl", "150"],
  ["century_gc_daily.pl", "20"],
  ["century_gc_daily.pl", "8"],
  ["century_gc_daily.pl", "count([xList2])"],
  ["century_gc_daily.pl", "element(['Ylist'],'LowerArrayPos')"],
  ["century_gc_daily.pl", "element(['Ylist'],'LowerArrayPos'+1)"],
  ["century_gc_daily.pl", "element([xlist],'LowerArrayPos')"],
  ["century_gc_daily.pl", "element([xlist],'LowerArrayPos'+1)"],
  ["century_gc_daily.pl", "element([xList2],'LowerArrayPos')"],
  ["century_gc_daily.pl", "element([xList2],'LowerArrayPos'+1)"],
  ["century_gc_daily.pl", "element([ylist],'LowerArrayPos')"],
  ["century_gc_daily.pl", "element([ylist],'LowerArrayPos'+1)"],
  ["century_gc_daily.pl", "sum(if [xList2]<'TSUM' then 1 else 0)"],
  ["century_gc_daily.pl", "table(index(1))"],
  ["century_gc_daily.pl", "yInterpolated"],
  ["century_gc_daily.pl", "yLower+(xSupplied-xLower)*(yHigher-yLower)/(xHigher-xLower)"],
  ["century_gc_weekly.pl", " 0.00013 *'TempMod'"],
  ["century_gc_weekly.pl", " 0.0038 *'TempMod'"],
  ["century_gc_weekly.pl", " 0.0117"],
  ["century_gc_weekly.pl", " 0.03"],
  ["century_gc_weekly.pl", " 0.094 *exp( -3.0*'StructLignin')*'TempMod'"],
  ["century_gc_weekly.pl", " 0.14 *(1- 0.75 *'Clay')*'TempMod'"],
  ["century_gc_weekly.pl", " 0.2"],
  ["century_gc_weekly.pl", " 0.35 *'TempMod'"],
  ["century_gc_weekly.pl", " 0.42"],
  ["century_gc_weekly.pl", " 0.45"],
  ["century_gc_weekly.pl", " 0.52"],
  ["century_gc_weekly.pl", " 0.7"],
  ["century_gc_weekly.pl", " 0.85 - 0.018 *'Lignin'/'Nitrogen'"],
  ["century_gc_weekly.pl", " 0.85 - 0.68 *'Clay'"],
  ["century_gc_weekly.pl", "'Active_Soil_C'*ka* 0.004"],
  ["century_gc_weekly.pl", "'Active_Soil_C'*ka*'Respa'"],
  ["century_gc_weekly.pl", "'Active_Soil_C'*ka*'UtilEffas'"],
  ["century_gc_weekly.pl", "'Active_Soil_C'+'Passive_Soil_C'+'Slow_Soil_C'"],
  ["century_gc_weekly.pl", "'Active_Soil_N'+'Passive_Soil_N'+'Slow_Soil_N'"],
  ["century_gc_weekly.pl", "'Carbon'/'Nitrogen'"],
  ["century_gc_weekly.pl", "'CO2_a'+'CO2s'+'CO2p'"],
  ["century_gc_weekly.pl", "'CO2_LiMet'+'CO2_LiSta'+'CO2_LiSts'"],
  ["century_gc_weekly.pl", "'DecNa'-'FNma'"],
  ["century_gc_weekly.pl", "'DecNsta'-'FNsta'"],
  ["century_gc_weekly.pl", "'DecNsts'-'FNsts'"],
  ["century_gc_weekly.pl", "'DecompNa'-'FNas'-'FNap'"],
  ["century_gc_weekly.pl", "'DecompNp'-'FNpa'"],
  ["century_gc_weekly.pl", "'DecompNs'-'FNsa'-'FNsp'"],
  ["century_gc_weekly.pl", "'Fap'/'CN_passive_SOM'"],
  ["century_gc_weekly.pl", "'Fas'/'CN_slow_SOM'"],
  ["century_gc_weekly.pl", "'Fas'/'UtilEffas'/'CN_active_SOM'"],
  ["century_gc_weekly.pl", "'Fma'/'CN_active_SOM'"],
  ["century_gc_weekly.pl", "'Fma'/'UtilEffm'/'CN_LiMet'"],
  ["century_gc_weekly.pl", "'Fpa'/'CN_active_SOM'"],
  ["century_gc_weekly.pl", "'Fpa'/'UtilEffp'/'CN_passive_SOM'"],
  ["century_gc_weekly.pl", "'Fsa'/'CN_active_SOM'"],
  ["century_gc_weekly.pl", "'Fsp'/'CN_passive_SOM'"],
  ["century_gc_weekly.pl", "'Fsp'/'UtilEffsp'/'CN_slow_SOM'"],
  ["century_gc_weekly.pl", "'Fsta'/'CN_active_SOM'"],
  ["century_gc_weekly.pl", "'Fsta'/'UtilEffSta'/'CN_LiSt'"],
  ["century_gc_weekly.pl", "'Fsts'/'CN_slow_SOM'"],
  ["century_gc_weekly.pl", "'Fsts'/'UtilEffsts'/'CN_LiSt'"],
  ["century_gc_weekly.pl", "'INIT_LiMetabolicN'"],
  ["century_gc_weekly.pl", "'INIT_Listructural_N'"],
  ["century_gc_weekly.pl", "'Initial_C'*'SplitMet'"],
  ["century_gc_weekly.pl", "'Initial_C'*'SplitMet'/'CNLiMet'"],
  ["century_gc_weekly.pl", "'Initial_C'*(1-'SplitMet')"],
  ["century_gc_weekly.pl", "'Initial_C'*(1-'SplitMet')/'CN_LiSt'"],
  ["century_gc_weekly.pl", "'Lignin'/(1-'SplitMet')"],
  ["century_gc_weekly.pl", "'LiMetabolic_C'*klim*'UtilEffm'"],
  ["century_gc_weekly.pl", "'LiMetabolic_C'*klim*(1-'UtilEffm')"],
  ["century_gc_weekly.pl", "'LiMetabolic_C'+'LiStructural_C'"],
  ["century_gc_weekly.pl", "'LiMetabolic_N'+'LiStructuralN'"],
  ["century_gc_weekly.pl", "'LiStructural_C'*'StructLignin'*klist*'UtilEffsts'"],
  ["century_gc_weekly.pl", "'LiStructural_C'*'StructLignin'*klist*(1-'UtilEffsts')"],
  ["century_gc_weekly.pl", "'LiStructural_C'*(1-'StructLignin')*klist*'UtilEffSta'"],
  ["century_gc_weekly.pl", "'LiStructural_C'*(1-'StructLignin')*klist*(1-'UtilEffSta')"],
  ["century_gc_weekly.pl", "'Mineral_N'/('Initial_C'/'Carbon'*'Nitrogen')*100"],
  ["century_gc_weekly.pl", "'Passive_Soil_C'*kp*'UtilEffp'"],
  ["century_gc_weekly.pl", "'Passive_Soil_C'*kp*(1-'UtilEffp')"],
  ["century_gc_weekly.pl", "'Slow_Soil_C'*ks*'UtilEffsa'"],
  ["century_gc_weekly.pl", "'Slow_Soil_C'*ks*'UtilEffsp'"],
  ["century_gc_weekly.pl", "'Slow_Soil_C'*ks*(1-'UtilEffsa'-'UtilEffsp')"],
  ["century_gc_weekly.pl", "'Soil_CO2'+'Litter_CO2'"],
  ["century_gc_weekly.pl", "'SplitMet'/(1/'Residue_CN'-(1-'SplitMet')/'CN_LiSt')"],
  ["century_gc_weekly.pl", "'Temperature'"],
  ["century_gc_weekly.pl", "'Total_SOM_N'+'Mineral_N'"],
  ["century_gc_weekly.pl", "(if'ArrayPosOfLowerXNW'<1 then 1 else (if'ArrayPosOfLowerXNW'=='ArraySize' then 'ArrayPosOfLowerXNW'-1 else 'ArrayPosOfLowerXNW'))"],
  ["century_gc_weekly.pl", "(if'Demandma'>'DecNa' then 'DecNa' else 'Demandma')"],
  ["century_gc_weekly.pl", "(if'Demandma'>'DecNa' then 'Demandma'-'DecNa' else 0)"],
  ["century_gc_weekly.pl", "(if'Demandsta'>'DecNsta' then 'DecNsta' else 'Demandsta')"],
  ["century_gc_weekly.pl", "(if'Demandsta'>'DecNsta' then 'Demandsta'-'DecNsta' else 0)"],
  ["century_gc_weekly.pl", "(if'Demandsts'>'DecNsts' then 'DecNsts' else 'Demandsts')"],
  ["century_gc_weekly.pl", "(if'Demandsts'>'DecNsts' then 'Demandsts'-'DecNsts' else 0)"],
  ["century_gc_weekly.pl", "[ 0.01, 0.05, 0.15, 0.3, 0.5, 0.7, 0.9,1, 0.95,0,0]"],
  ["century_gc_weekly.pl", "[0,5,10,15,20,25,30,35,40,45,50]"],
  ["century_gc_weekly.pl", "[xtable]"],
  ["century_gc_weekly.pl", "[ytable]"],
  ["century_gc_weekly.pl", "0"],
  ["century_gc_weekly.pl", "1-'Respa'- 0.004"],
  ["century_gc_weekly.pl", "100"],
  ["century_gc_weekly.pl", "11"],
  ["century_gc_weekly.pl", "150"],
  ["century_gc_weekly.pl", "20"],
  ["century_gc_weekly.pl", "8"],
  ["century_gc_weekly.pl", "count([xList2])"],
  ["century_gc_weekly.pl", "element(['Ylist'],'LowerArrayPos')"],
  ["century_gc_weekly.pl", "element(['Ylist'],'LowerArrayPos'+1)"],
  ["century_gc_weekly.pl", "element([xlist],'LowerArrayPos')"],
  ["century_gc_weekly.pl", "element([xlist],'LowerArrayPos'+1)"],
  ["century_gc_weekly.pl", "element([xList2],'LowerArrayPos')"],
  ["century_gc_weekly.pl", "element([xList2],'LowerArrayPos'+1)"],
  ["century_gc_weekly.pl", "element([ylist],'LowerArrayPos')"],
  ["century_gc_weekly.pl", "element([ylist],'LowerArrayPos'+1)"],
  ["century_gc_weekly.pl", "sum(if [xList2]<'TSUM' then 1 else 0)"],
  ["century_gc_weekly.pl", "table(index(1))"],
  ["century_gc_weekly.pl", "yInterpolated"],
  ["century_gc_weekly.pl", "yLower+(xSupplied-xLower)*(yHigher-yLower)/(xHigher-xLower)"],
  ["chao.pl", " 1.5"],
  ["chao.pl", "gain*level*(1-level/100)"],
  ["chao.pl", "rand_const(50, 50.000001)"],
  ["chemical1.pl", " 0.01 *'CO2'*2*(temperature/10)"],
  ["chemical1.pl", "0"],
  ["chemical1.pl", "100"],
  ["chemical1.pl", "6*rate"],
  ["chemical1.pl", "rate"],
  ["competition1.pl", " 0.005"],
  ["competition1.pl", " 0.01"],
  ["competition1.pl", " 0.02"],
  ["competition1.pl", " 0.1"],
  ["competition1.pl", "1"],
  ["competition1.pl", "r1*'N1'*(1-b1*'N1'-c1*'N2')"],
  ["competition1.pl", "r2*'N2'*(1-b2*'N1'-c2*'N1')"],
  ["daisyworld1.pl", " 0.003265"],
  ["daisyworld1.pl", " 0.01"],
  ["daisyworld1.pl", " 0.25"],
  ["daisyworld1.pl", " 0.3"],
  ["daisyworld1.pl", " 0.5"],
  ["daisyworld1.pl", " 0.75"],
  ["daisyworld1.pl", " 0.8"],
  ["daisyworld1.pl", " 22.5"],
  ["daisyworld1.pl", " 5.67 *pow(10,-8)"],
  ["daisyworld1.pl", "1-black_area-white_area"],
  ["daisyworld1.pl", "20"],
  ["daisyworld1.pl", "917"],
  ["daisyworld1.pl", "black_albedo*black_area+white_albedo*white_area+bare_albedo*bare_area"],
  ["daisyworld1.pl", "black_area*bare_area*black_gr"],
  ["daisyworld1.pl", "d*black_area"],
  ["daisyworld1.pl", "d*white_area"],
  ["daisyworld1.pl", "pow(1-k1*(best_temp-black_temp),2)"],
  ["daisyworld1.pl", "pow(1-k1*(best_temp-white_temp),2)"],
  ["daisyworld1.pl", "pow(solar_const*luminosity*(1-planet_albedo)/stefan, 0.25)-273"],
  ["daisyworld1.pl", "q1*(planet_albedo-black_albedo)+effective_temp"],
  ["daisyworld1.pl", "q1*(planet_albedo-white_albedo)+effective_temp"],
  ["daisyworld1.pl", "white_area*bare_area*white_gr"],
  ["data_specified_assoc1.pl", "[1,1,2]"],
  ["data_specified_assoc1.pl", "[3,4,4]"],
  ["data_specified_assoc1.pl", "any(var1==[hs] and f==[fs])"],
  ["data_specified_assoc1.pl", "index(1)"],
  ["data_specified_assoc2.pl", "(any('ID'==['IDa'] and 'ID_0'==['IDb']) or any('ID'==['IDb'] and 'ID_0'==['IDa']))"],
  ["data_specified_assoc2.pl", "[1,2,3]"],
  ["data_specified_assoc2.pl", "[2,3,4]"],
  ["data_specified_assoc2.pl", "index(1)"],
  ["dave1.pl", " -1*floor(rand(1, 2.9999))"],
  ["dave1.pl", " 0.1 *money"],
  ["dave1.pl", "(bank==bank_id)"],
  ["dave1.pl", "(bank==bank_id&&request>0)"],
  ["dave1.pl", "(if mediator==mediator_chosen then bank else 0)"],
  ["dave1.pl", "(if mediator==mediator_chosen then request else 0)"],
  ["dave1.pl", "(if rand_var(0,1)< 0.2 then 1 else 0)"],
  ["dave1.pl", "(rand_const(0,1)< 0.5)"],
  ["dave1.pl", "0"],
  ["dave1.pl", "100"],
  ["dave1.pl", "100000"],
  ["dave1.pl", "2"],
  ["dave1.pl", "4"],
  ["dave1.pl", "greatest({mediator})"],
  ["dave1.pl", "index(1)"],
  ["dave1.pl", "mediator_chosen"],
  ["dave1.pl", "mediator_id"],
  ["dave1.pl", "sum({bank})"],
  ["diffusion.pl", "(hypots<bounce_distance&&rightway)"],
  ["diffusion.pl", "(if index(1)==1 then fmod(25*(index(2)-1), 112.5) else  16.66*int((index(2)-1)/ 4.5))"],
  ["diffusion.pl", "(index(1)<index(2))"],
  ["diffusion.pl", "[p]"],
  ["diffusion.pl", "[posns_b1]-[posns_b2]"],
  ["diffusion.pl", "0"],
  ["diffusion.pl", "10*mass*(if p<0 then 0-p elseif p>100 then 100-p else 0)"],
  ["diffusion.pl", "15"],
  ["diffusion.pl", "a+element(['Actions'],index(1))+rand_var(-10,10)"],
  ["diffusion.pl", "any(index(1)==[2,3,4,5,7,8,9,12,13,14,17,18,22,23,27,32])"],
  ["diffusion.pl", "element([p],1)"],
  ["diffusion.pl", "element([p],2)"],
  ["diffusion.pl", "force/mass"],
  ["diffusion.pl", "forces*[distances]/hypots"],
  ["diffusion.pl", "green_"],
  ["diffusion.pl", "hypot(element([distances],1),element([distances],2))"],
  ["diffusion.pl", "not green_"],
  ["diffusion.pl", "pow(bounce_distance/hypots,4)"],
  ["diffusion.pl", "sizes"],
  ["diffusion.pl", "sizes_b1+sizes_b2"],
  ["diffusion.pl", "sizes*sizes/100"],
  ["diffusion.pl", "sizes/10"],
  ["diffusion.pl", "sum([energy])"],
  ["diffusion.pl", "sum([v]^2)"],
  ["diffusion.pl", "sum({[comps_b1]})-sum({[comps_b2]})"],
  ["diffusion.pl", "v"],
  ["diffusion.pl", "x"],
  ["diffusion.pl", "x/10+45"],
  ["diffusion.pl", "y"],
  ["diffusion.pl", "y/10+45"],
  ["drainage1.pl", "'N_cells'/x_length"],
  ["drainage1.pl", "(if col>=1 and col<=x_length and row>=1 and row<=y_length then element([h],nid) else  1.0e+300)"],
  ["drainage1.pl", "(if nid_min==1 then 225 elseif nid_min==2 then 180 elseif nid_min==3 then 135 elseif nid_min==4 then 270 elseif nid_min==6 then 90 elseif nid_min==7 then 315 elseif nid_min==8 then 0 elseif nid_min==9 then 45 else -1)"],
  ["drainage1.pl", "[height]"],
  ["drainage1.pl", "100"],
  ["drainage1.pl", "col+element([-1,0,1,-1,0,1,-1,0,1],index(1))"],
  ["drainage1.pl", "index(1)"],
  ["drainage1.pl", "index(1)-(row-1)*x_length"],
  ["drainage1.pl", "int((index(1)-1)/y_length)+1"],
  ["drainage1.pl", "int(rand_const(0,10)+1)"],
  ["drainage1.pl", "posleast([h])"],
  ["drainage1.pl", "row+element([-1,-1,-1,0,0,0,1,1,1],index(1))"],
  ["drainage1.pl", "size(cell)"],
  ["drainage1.pl", "x_length*(row-1)+col"],
  ["edinburgh1.pl", " 0.2 *landfill"],
  ["edinburgh1.pl", " 0.5 *emissions+100*industrial_capital+ 0.5 *decomposition"],
  ["edinburgh1.pl", " 1.0e-06 *total_cars"],
  ["edinburgh1.pl", "0"],
  ["edinburgh1.pl", "1"],
  ["edinburgh1.pl", "10"],
  ["edinburgh1.pl", "1000"],
  ["edinburgh1.pl", "1000000"],
  ["edinburgh1.pl", "15000"],
  ["edinburgh1.pl", "2"],
  ["edinburgh1.pl", "500000"],
  ["edinburgh1.pl", "9000"],
  ["edinburgh1.pl", "cars_per_head*population_size"],
  ["edinburgh1.pl", "emissions*graph(wind)"],
  ["edinburgh1.pl", "graph(road_pricing)"],
  ["edinburgh1.pl", "graph(uplift_charge)*population_size"],
  ["edinburgh1.pl", "temperature*age_structure*graph(pollution)"],
  ["embryo1.pl", " 0.001"],
  ["embryo1.pl", " 0.001 *activin"],
  ["embryo1.pl", " 0.1"],
  ["embryo1.pl", " 0.5"],
  ["embryo1.pl", "(abs(row-row_0)<=1 and abs(col-col_0)<=1 and not (row==row_0 and col==col_0))"],
  ["embryo1.pl", "(if activin>100 then 100 else activin)"],
  ["embryo1.pl", "(if black>enzyme/dt(1) then enzyme else 0)"],
  ["embryo1.pl", "(if max_SMAD>1500 then 3 elseif max_SMAD>500 then 2 else 1)"],
  ["embryo1.pl", "(if time(1)<'SMAD_competency_time' then k_SMAD_production*bound_receptors else 0)"],
  ["embryo1.pl", "(if time(1)<10 and index(1)==46 then k_activin_create else 0)"],
  ["embryo1.pl", "(if'SMAD'>prev(1) then 'SMAD' else prev(1))"],
  ["embryo1.pl", "0"],
  ["embryo1.pl", "1"],
  ["embryo1.pl", "100"],
  ["embryo1.pl", "5*col"],
  ["embryo1.pl", "5*row"],
  ["embryo1.pl", "500"],
  ["embryo1.pl", "activin_outflow/n_neighbours"],
  ["embryo1.pl", "black_outflow/8"],
  ["embryo1.pl", "black/300"],
  ["embryo1.pl", "floor((index(1)-1)/20)+1"],
  ["embryo1.pl", "fmod(index(1)-1,20)+1"],
  ["embryo1.pl", "k_activin_binding*activin"],
  ["embryo1.pl", "k_activin_breakdown*activin"],
  ["embryo1.pl", "k_activin_outflow*activin*n_neighbours/8"],
  ["embryo1.pl", "k_black_excrete*black"],
  ["embryo1.pl", "k_black_outflow*black"],
  ["embryo1.pl", "k_SMAD_breakdown*'SMAD'"],
  ["embryo1.pl", "k_white_to_black*white*black"],
  ["embryo1.pl", "rand_const(97,103)"],
  ["embryo1.pl", "sum({one_0})"],
  ["embryo1.pl", "sum({white_interflow_0})"],
  ["feeding1.pl", "any(index(1)==[eating_animals]&&index(2)==[eaten_plants])"],
  ["feeding1.pl", "biomass"],
  ["feeding1.pl", "element([1,1,2,2,3,4],index(1))"],
  ["feeding1.pl", "element([1,2,2,3,1,2],index(1))"],
  ["feeding1.pl", "element([10,20,30,40],index(1))"],
  ["feeding1.pl", "element([11,12,13,14,15,16],index(1))"],
  ["feeding1.pl", "element([2,4,6],index(1))"],
  ["feeding1.pl", "element([palatabilities],index)"],
  ["feeding1.pl", "floor(rand_const(0,10))"],
  ["feeding1.pl", "greatest(if index(1)==[eating_animals]&&index(2)==[eaten_plants] then [indexes] else 0)"],
  ["feeding1.pl", "greatest(if index(1)==[eating_animals]&&index(2)==[eaten_plants] then [palatabilities] else 0)"],
  ["feeding1.pl", "index(1)"],
  ["feeding1.pl", "pop_size"],
  ["feeding1.pl", "sum({biomass})"],
  ["feeding1.pl", "sum({eaten})"],
  ["feeding1.pl", "sum({pop_size})"],
  ["grace1.pl", "[[ 0.02, 0.01, 0.03, 0.01, 0.01],[ 0.01, 0.01, 0.01, 0.01, 0.04],[ 0.01, 0.02, 0.01, 0.04, 0.01],[ 0.01, 0.01, 0.01, 0.05, 0.01],[ 0.01, 0.04, 0.01, 0.01, 0.02]]"],
  ["grace1.pl", "[biomass]"],
  ["grace1.pl", "element([ 0.6, 0.5, 0.4, 0.3, 0.2],index(1))"],
  ["grace1.pl", "element([1,2,4,8,16],index(1))"],
  ["grace1.pl", "r*biomass*(1-inhib)"],
  ["grace1.pl", "sum(element([[c]],index(1))*[biomasses])"],
  ["gridspread1.pl", " 0.05 *amount"],
  ["gridspread1.pl", "(if index(1)==35 then 1000 else 0)"],
  ["gridspread1.pl", "[col]"],
  ["gridspread1.pl", "[outflow]/8"],
  ["gridspread1.pl", "[row]"],
  ["gridspread1.pl", "floor((index(1)-1)/10)+1"],
  ["gridspread1.pl", "index(1)-10*(row-1)"],
  ["gridspread1.pl", "sum(if abs([rows]-row)< 1.5 and abs([cols]-col)< 1.5 then [interflows] else 0)"],
  ["hexagon.pl", " -a-b"],
  ["hexagon.pl", " 0.1 +tREE*tREE/2000"],
  ["hexagon.pl", "(a_0==a-1,b_0==b+1,c_0==c)", 1],
  ["hexagon.pl", "(off=sqrt(3/4),x+10*element([0,off,off,0,-off,-off],index(1)))"],
  ["hexagon.pl", "(z> -5&&z<5)"],
  ["hexagon.pl", "10"],
  ["hexagon.pl", "50+10*(a-c)* 0.866"],
  ["hexagon.pl", "50+10*b* 1.5"],
  ["hexagon.pl", "biomass"],
  ["hexagon.pl", "index(1)-5"],
  ["hexagon.pl", "index(2)-5"],
  ["hexagon.pl", "sum_biomass/20"],
  ["hexagon.pl", "sum({var12_0})"],
  ["hexagon.pl", "y+10*element([1, 0.5, -0.5,-1, -0.5, 0.5],index(1))"],
  ["homeostasis1.pl", " 0.03 *body_heat"],
  ["homeostasis1.pl", " 0.1 *body_temperature"],
  ["homeostasis1.pl", "(if body_temperature<set_point then 10 else 0)"],
  ["homeostasis1.pl", "1000"],
  ["homeostasis1.pl", "37"],
  ["hunter1.pl", "(if (x<0;x>100;y<0;y>100) then 1 else 0)", 1],
  ["hunter1.pl", "(if outside==1 then  3.14/dt(1) else rand( -0.4, 0.4)/dt(1))"],
  ["hunter1.pl", "(if outside==1 then speed*cos(dir+ 3.14) else speed*cos(dir))"],
  ["hunter1.pl", "(if outside==1 then speed*sin(dir+ 3.14) else speed*sin(dir))"],
  ["hunter1.pl", "3"],
  ["hunter1.pl", "5"],
  ["hunter1.pl", "rand(0, 6.28)"],
  ["hunter1.pl", "rand(30,70)"],
  ["indivpop1.pl", "(if rand_var(0,1)<r then 1 else 0)"],
  ["indivpop1.pl", "1"],
  ["indivpop1.pl", "2"],
  ["indivpop1.pl", "graph(age)"],
  ["indivpop1.pl", "graph(age)*(1-pop_size/100)"],
  ["indivpop1.pl", "m"],
  ["indivpop1.pl", "sum({one})"],
  ["indivpop1.pl", "time(1)-init_time(1)"],
  ["johadP.pl", " 0.5"],
  ["johadP.pl", " 1200.0"],
  ["johadP.pl", "'Area_not_harnessed'*typical_surface_flow*10"],
  ["johadP.pl", "'Village_population'*labour_contributed_per_capita"],
  ["johadP.pl", "(if capacity<=0 or stored_water<=0 then 0 else depth*(stored_water/capacity)^(1/3))"],
  ["johadP.pl", "(if count({depth_when_full})==0 then 0 else greatest({depth_when_full}))"],
  ["johadP.pl", "(if count({surface_area_when_full})==0 then 0 else greatest({surface_area_when_full}))"],
  ["johadP.pl", "(if depth<=0 then 0 else surface_area_when_full*water_depth/depth)"],
  ["johadP.pl", "(if effort<=0 then 0 else labour_input/effort)"],
  ["johadP.pl", "(if fmod(time(1),360)>0 then prev(1) else makearray(( 1.4+( 3.95- 1.4)*element([rainrand],fmod(time(1),10000)+place_in(1)))^3*(if 30*element([rainrand],fmod(time(1),10000)+place_in(1))<24 then 1 else 0),30))"],
  ["johadP.pl", "(if fmod(time(1),360)>0 then prev(1) else makearray(floor(90*element([randday],fmod(time(1),10000)+place_in(1))),30)+[0,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3]*90+1)"],
  ["johadP.pl", "(if init_time(1)==time(1) or last(wetted_area)<wetted_area then 10 else 1)* 0.025 *wetted_area*(1-proportion^2)"],
  ["johadP.pl", "(if last(today_s_rainfall)>typical_infiltration then today_s_rainfall else max(0,today_s_rainfall-typical_infiltration))* 0.5"],
  ["johadP.pl", "(if opposition>=5 or count({stored_water})>=10 then 0 else motivation*(10-opposition)/1000)"],
  ["johadP.pl", "(if proportion> 0.7 then  0.003*ground_water*(proportion- 0.4) else 0)"],
  ["johadP.pl", "(if rand_var(0,1)<opposition/25/360 then 1 else 0)"],
  ["johadP.pl", "(if stored_water>capacity or stored_water+inflow* 0.9 >capacity or stored_water+inflow>capacity* 1.2 then max(stored_water+inflow* 0.9 -capacity,stored_water+inflow-capacity* 1.2) else 0)"],
  ["johadP.pl", "(if streams<1 then streams else (streams+overland_flow)*(if streams>10 then  0.5 else  0.9))"],
  ["johadP.pl", "(if time(1)==0 then 1200 else last('Area_not_harnessed'))"],
  ["johadP.pl", "(if time(1)==0 then depth else max(last(deepest_yet),depth))*rand_var( 0.9, 1.2)"],
  ["johadP.pl", "(if time(1)==0 then tank_area else max(last(biggest_yet),tank_area))*rand_var( 0.9, 1.2)"],
  ["johadP.pl", "(if time(1)==init_time(1) then  0.5*typical_surface_flow else  0.5*(typical_surface_flow+last(typical_surface_flow)))"],
  ["johadP.pl", "(if time(1)==init_time(1) then next_area else prev(1))"],
  ["johadP.pl", "(if time(1)==init_time(1) then next_depth else prev(1))"],
  ["johadP.pl", "(if village_water_use<ground_water then village_water_use else 0)"],
  ["johadP.pl", "0"],
  ["johadP.pl", "10"],
  ["johadP.pl", "10*catchment_area*surface_flow"],
  ["johadP.pl", "100"],
  ["johadP.pl", "100*sum([days_of_river_flow])/count([days_of_river_flow])"],
  ["johadP.pl", "100*sum([days_with_water_in_tank])/count([days_with_water_in_tank])"],
  ["johadP.pl", "150"],
  ["johadP.pl", "3"],
  ["johadP.pl", "300"],
  ["johadP.pl", "4*sqrt(area*depth^2+area^2/4)/2"],
  ["johadP.pl", "5"],
  ["johadP.pl", "720000"],
  ["johadP.pl", "cumulative_river_flow/1000000"],
  ["johadP.pl", "current_surface_area*((1-cos(2*pi('')*time(1)/360))*5+5)/1000"],
  ["johadP.pl", "ground_water/capacity"],
  ["johadP.pl", "makearray(if place_in(1)==fmod(time(1),360)+1 then (if river_flow>1 then 1 else 0) elseif time(1)==0 then (if place_in(1)>210 and place_in(1)<=234 then 1 else 0) else element(prev(1),place_in(1)),360)"],
  ["johadP.pl", "makearray(if place_in(1)==fmod(time(1),360)+1 then (if water_drawn_from_wells>0 then 1 else 0) elseif time(1)==0 then 0 else element(prev(1),place_in(1)),360)"],
  ["johadP.pl", "makearray(rand_const(0,1),10000)"],
  ["johadP.pl", "max(0,'Total_catchment_area'-sum({catchment_area}))"],
  ["johadP.pl", "min(rand_const(80,120),area_left)"],
  ["johadP.pl", "next_depth^2*next_area/10"],
  ["johadP.pl", "proportion*10"],
  ["johadP.pl", "river_flow^ 0.35 /25"],
  ["johadP.pl", "sum(makearray(if fmod(time(1),360)+1==element([rain_days],place_in(1)) then element([rain_amount],place_in(1)) else 0,30))"],
  ["johadP.pl", "surface_area_when_full*depth/3"],
  ["johadP.pl", "water_use_per_capita*'Village_population'"],
  ["labour_by_priority1.pl", "(if ['Tasks_req']>0 then [time_allocated]/['Tasks_req'] else 94)"],
  ["labour_by_priority1.pl", "(if sum_of_higher_priority_times+time_required<time_available then time_required elseif sum_of_higher_priority_times<time_available then sum_of_higher_priority_times+time_required-time_available else 0)"],
  ["labour_by_priority1.pl", "(priority>priority_0)"],
  ["labour_by_priority1.pl", "element([priorities],index(1))"],
  ["labour_by_priority1.pl", "element([time_required],index(1))"],
  ["labour_by_priority1.pl", "sum({value_0})"],
  ["labour_by_priority1.pl", "value"],
  ["lagrangian1.pl", "(if max(abs(50-x),abs(50-y))>50 then 1 else 0)"],
  ["lagrangian1.pl", "(if outside==1 then  3.14/dt(1) else (if (x>30,x<50,y<70) then  0.4*( 1.57-fmod(abs(dir), 6.28)) else  0.4*( 3.14-fmod(abs(dir), 6.28))+rand( -0.15, 0.15)/dt(1)))", 1],
  ["lagrangian1.pl", "(if outside==1 then speed*cos(dir+ 3.14) else speed*cos(dir))"],
  ["lagrangian1.pl", "(if outside==1 then speed*sin(dir+ 3.14) else speed*sin(dir))"],
  ["lagrangian1.pl", "(x<0)"],
  ["lagrangian1.pl", "1"],
  ["lagrangian1.pl", "10"],
  ["lagrangian1.pl", "5"],
  ["lagrangian1.pl", "80"],
  ["lagrangian1.pl", "rand(0, 6.28)"],
  ["lagrangian1.pl", "rand(10,90)"],
  ["lamos1a.pl", "(abs(row-row_0)+abs(col-col_0)==1)"],
  ["lamos1a.pl", "(abs(row-row_0)<=1 and abs(col-col_0)<=1 and! (row==row_0 and col==col_0))"],
  ["lamos1a.pl", "(abs(time(1)-10)<0.001)"],
  ["lamos1a.pl", "(check_spark and spark_patch==index(1))"],
  ["lamos1a.pl", "(check_spark or burning)"],
  ["lamos1a.pl", "(crossover or new_fire)"],
  ["lamos1a.pl", "(distance<3)"],
  ["lamos1a.pl", "(fuel_load>rand_const(min_for_fire,always_starts))"],
  ["lamos1a.pl", "(if ([row_neighbours]>0,[row_neighbours]<=nrow,[col_neighbours]>0,[col_neighbours]<=ncol)then ncol*([row_neighbours]-1)+[col_neighbours]else index(1))", 1],
  ["lamos1a.pl", "(if any({burning})then element(sum({[fuel_load_lost]}),index(1))elseif fmod(time(1),dt(1))>0 and fmod(time(1),dt(1))<1.5*dt(2)then 0 else prev(1))"],
  ["lamos1a.pl", "(if any({burning})then sum({[fuel_load_lost]})elseif time_in_2>0 and time_in_2<1.5*dt(2)then 0 else prev(1))"],
  ["lamos1a.pl", "(if fire then fuel_load*burnt_per_step/dt(2)else 0)"],
  ["lamos1a.pl", "(if water>100 then 1 elseif water<50 then 0 else(water-50)/50)"],
  ["lamos1a.pl", "(if water>100 then water_demand else water_demand*water/100)"],
  ["lamos1a.pl", "(neighbour_burns and catches)"],
  ["lamos1a.pl", "(rand_var(0,1)<0.7*max(0,min(1,(fuel_load-min_for_fire)/(always_catch-min_for_fire))))"],
  ["lamos1a.pl", "(spark_ and fmod(time(1),dt(1))<dt(2))"],
  ["lamos1a.pl", "(spark_here and starts)"],
  ["lamos1a.pl", "[[0.005,0.003,0.006,0.007,0.006],[0.002,0.005,0.006,0.007,0.006],[0.002,0.002,0.005,0.006,0.002],[0.002,0.002,0.003,0.004,0.002],[0.002,0.002,0.003,0.002,0.005]]"],
  ["lamos1a.pl", "[0.1,0.1,0.1,0.1,0.1]"],
  ["lamos1a.pl", "[0.2,0.2,0.15,0.1,0.05]"],
  ["lamos1a.pl", "[0.5,0.5,0.5,0.5,0.5]"],
  ["lamos1a.pl", "[0.7,0.6,0.25,0.2,0.2]"],
  ["lamos1a.pl", "[10.0,10.0,10.0,10.0,10.0]"],
  ["lamos1a.pl", "[5,5,4,3,2]"],
  ["lamos1a.pl", "[70.0,60.0,25.0,20.0,20.0]"],
  ["lamos1a.pl", "[col,col+1,col,col-1]"],
  ["lamos1a.pl", "[fuel_lost]-prev(1)"],
  ["lamos1a.pl", "[number]"],
  ["lamos1a.pl", "[old_fire]"],
  ["lamos1a.pl", "[row-1,row,row+1,row]"],
  ["lamos1a.pl", "[seeds_dispersing]"],
  ["lamos1a.pl", "[seeds_produced]*[k1]*exp(-1*[k2]*distance)"],
  ["lamos1a.pl", "0"],
  ["lamos1a.pl", "0.01*(seeds_staying+seeds_in)*(1-feedback)*water_multiplier"],
  ["lamos1a.pl", "0.2*water"],
  ["lamos1a.pl", "0.6"],
  ["lamos1a.pl", "100"],
  ["lamos1a.pl", "1000"],
  ["lamos1a.pl", "15"],
  ["lamos1a.pl", "1500"],
  ["lamos1a.pl", "200-10*col*sin(0.7*row)"],
  ["lamos1a.pl", "2500"],
  ["lamos1a.pl", "5"],
  ["lamos1a.pl", "any([other_fires])"],
  ["lamos1a.pl", "any(element([other_fires],[neighbours]))"],
  ["lamos1a.pl", "element([[cs]],index(1))"],
  ["lamos1a.pl", "element([[neighbours]],index(1))"],
  ["lamos1a.pl", "element([fuel_load],index(1))"],
  ["lamos1a.pl", "element([fuel_lost],index(1))"],
  ["lamos1a.pl", "element([ms],index(1))"],
  ["lamos1a.pl", "element([number],1)"],
  ["lamos1a.pl", "element([number],2)"],
  ["lamos1a.pl", "element([number],3)"],
  ["lamos1a.pl", "element([number],4)"],
  ["lamos1a.pl", "element([number],5)"],
  ["lamos1a.pl", "element([rs],index(1))"],
  ["lamos1a.pl", "element([seeds_per_indiv],index(1))*number"],
  ["lamos1a.pl", "element(sum({[fuel_load_lost]}),index(1))"],
  ["lamos1a.pl", "element(sum({[seeds_transfer_0]}),index(1))"],
  ["lamos1a.pl", "elevation-elevation_0"],
  ["lamos1a.pl", "floor((index(1)-1)/15)+1"],
  ["lamos1a.pl", "floor((index(1)-1)/30)+1"],
  ["lamos1a.pl", "floor((index(1)-1)/nrow)+1"],
  ["lamos1a.pl", "floor(rand_const(1000,3000))"],
  ["lamos1a.pl", "fmod(index(1)-1,15)+1"],
  ["lamos1a.pl", "fmod(index(1)-1,30)+1"],
  ["lamos1a.pl", "fmod(index(1)-1,ncol)+1"],
  ["lamos1a.pl", "fmod(time(1),dt(1))"],
  ["lamos1a.pl", "fraction_lost*number"],
  ["lamos1a.pl", "fuel_lost/fuel_load"],
  ["lamos1a.pl", "hypot(row-row_0,col-col_0)"],
  ["lamos1a.pl", "index(1)"],
  ["lamos1a.pl", "int(rand_var(1,size(fire_patch)+1))"],
  ["lamos1a.pl", "last(fire)"],
  ["lamos1a.pl", "m*number"],
  ["lamos1a.pl", "max(0,0.005*elevation_diff*water)"],
  ["lamos1a.pl", "min(1,1/[dispersal_distance])"],
  ["lamos1a.pl", "old_fire"],
  ["lamos1a.pl", "rain"],
  ["lamos1a.pl", "rand_const(1000,3000)"],
  ["lamos1a.pl", "seeds_produced-seeds_dispersing"],
  ["lamos1a.pl", "seeds_produced*element([dispersability],index(1))"],
  ["lamos1a.pl", "sum([c]*[numbers])"],
  ["lamos1a.pl", "sum([number]*[fuel_per_indiv])"],
  ["lamos1a.pl", "sum([water_use]*[number])"],
  ["lamos1a.pl", "sum({interflow_0})"],
  ["lamos1a.pl", "sum({interflow})"],
  ["lamos1a.pl", "water"],
  ["lamos1b.pl", "(abs(row-row_0)+abs(col-col_0)==1)"],
  ["lamos1b.pl", "(abs(row-row_0)<=1 and abs(col-col_0)<=1 and! (row==row_0 and col==col_0))"],
  ["lamos1b.pl", "(abs(time(1)-10)<0.001)"],
  ["lamos1b.pl", "(check_spark and spark_patch==index(1))"],
  ["lamos1b.pl", "(check_spark or burning)"],
  ["lamos1b.pl", "(crossover or new_fire)"],
  ["lamos1b.pl", "(distance<3)"],
  ["lamos1b.pl", "(fuel_load>rand_const(min_for_fire,always_starts))"],
  ["lamos1b.pl", "(if ([row_neighbours]>0,[row_neighbours]<=nrow,[col_neighbours]>0,[col_neighbours]<=ncol)then ncol*([row_neighbours]-1)+[col_neighbours]else index(1))", 1],
  ["lamos1b.pl", "(if any({burning})then element(sum({[fuel_load_lost]}),index(1))elseif fmod(time(1),dt(1))>0 and fmod(time(1),dt(1))<1.5*dt(2)then 0 else prev(1))"],
  ["lamos1b.pl", "(if any({burning})then sum({[fuel_load_lost]})elseif time_in_2>0 and time_in_2<1.5*dt(2)then 0 else prev(1))"],
  ["lamos1b.pl", "(if fire then fuel_load*burnt_per_step/dt(2)else 0)"],
  ["lamos1b.pl", "(if water>100 then 1 elseif water<50 then 0 else(water-50)/50)"],
  ["lamos1b.pl", "(if water>100 then water_demand else water_demand*water/100)"],
  ["lamos1b.pl", "(neighbour_burns and catches)"],
  ["lamos1b.pl", "(rand_var(0,1)<0.7*max(0,min(1,(fuel_load-min_for_fire)/(always_catch-min_for_fire))))"],
  ["lamos1b.pl", "(spark_ and fmod(time(1),dt(1))<dt(2))"],
  ["lamos1b.pl", "(spark_here and starts)"],
  ["lamos1b.pl", "[[0.005,0.003,0.006,0.007,0.006],[0.002,0.005,0.006,0.007,0.006],[0.002,0.002,0.005,0.006,0.002],[0.002,0.002,0.003,0.004,0.002],[0.002,0.002,0.003,0.002,0.005]]"],
  ["lamos1b.pl", "[0.1,0.1,0.1,0.1,0.1]"],
  ["lamos1b.pl", "[0.2,0.2,0.15,0.1,0.05]"],
  ["lamos1b.pl", "[0.5,0.5,0.5,0.5,0.5]"],
  ["lamos1b.pl", "[0.7,0.6,0.25,0.2,0.2]"],
  ["lamos1b.pl", "[10.0,10.0,10.0,10.0,10.0]"],
  ["lamos1b.pl", "[5,5,4,3,2]"],
  ["lamos1b.pl", "[70.0,60.0,25.0,20.0,20.0]"],
  ["lamos1b.pl", "[col,col+1,col,col-1]"],
  ["lamos1b.pl", "[fuel_lost]-prev(1)"],
  ["lamos1b.pl", "[number]"],
  ["lamos1b.pl", "[old_fire]"],
  ["lamos1b.pl", "[row-1,row,row+1,row]"],
  ["lamos1b.pl", "[seeds_dispersing]"],
  ["lamos1b.pl", "[seeds_produced]*[k1]*exp(-1*[k2]*distance)"],
  ["lamos1b.pl", "0"],
  ["lamos1b.pl", "0.01*(seeds_staying+seeds_in)*(1-feedback)*water_multiplier"],
  ["lamos1b.pl", "0.2*water"],
  ["lamos1b.pl", "0.6"],
  ["lamos1b.pl", "100"],
  ["lamos1b.pl", "1000"],
  ["lamos1b.pl", "1500"],
  ["lamos1b.pl", "200-10*col*sin(0.7*row)"],
  ["lamos1b.pl", "2500"],
  ["lamos1b.pl", "40"],
  ["lamos1b.pl", "5"],
  ["lamos1b.pl", "any([other_fires])"],
  ["lamos1b.pl", "any(element([other_fires],[neighbours]))"],
  ["lamos1b.pl", "element([[cs]],index(1))"],
  ["lamos1b.pl", "element([[neighbours]],index(1))"],
  ["lamos1b.pl", "element([fuel_load],index(1))"],
  ["lamos1b.pl", "element([fuel_lost],index(1))"],
  ["lamos1b.pl", "element([ms],index(1))"],
  ["lamos1b.pl", "element([number],1)"],
  ["lamos1b.pl", "element([number],2)"],
  ["lamos1b.pl", "element([number],3)"],
  ["lamos1b.pl", "element([number],4)"],
  ["lamos1b.pl", "element([number],5)"],
  ["lamos1b.pl", "element([rs],index(1))"],
  ["lamos1b.pl", "element([seeds_per_indiv],index(1))*number"],
  ["lamos1b.pl", "element(sum({[fuel_load_lost]}),index(1))"],
  ["lamos1b.pl", "element(sum({[seeds_transfer_0]}),index(1))"],
  ["lamos1b.pl", "elevation-elevation_0"],
  ["lamos1b.pl", "floor((index(1)-1)/30)+1"],
  ["lamos1b.pl", "floor((index(1)-1)/40)+1"],
  ["lamos1b.pl", "floor((index(1)-1)/nrow)+1"],
  ["lamos1b.pl", "floor(rand_const(1000,3000))"],
  ["lamos1b.pl", "fmod(index(1)-1,30)+1"],
  ["lamos1b.pl", "fmod(index(1)-1,40)+1"],
  ["lamos1b.pl", "fmod(index(1)-1,ncol)+1"],
  ["lamos1b.pl", "fmod(time(1),dt(1))"],
  ["lamos1b.pl", "fraction_lost*number"],
  ["lamos1b.pl", "fuel_lost/fuel_load"],
  ["lamos1b.pl", "hypot(row-row_0,col-col_0)"],
  ["lamos1b.pl", "index(1)"],
  ["lamos1b.pl", "int(rand_var(1,size(fire_patch)+1))"],
  ["lamos1b.pl", "last(fire)"],
  ["lamos1b.pl", "m*number"],
  ["lamos1b.pl", "max(0,0.005*elevation_diff*water)"],
  ["lamos1b.pl", "min(1,1/[dispersal_distance])"],
  ["lamos1b.pl", "old_fire"],
  ["lamos1b.pl", "rain"],
  ["lamos1b.pl", "rand_const(1000,3000)"],
  ["lamos1b.pl", "seeds_produced-seeds_dispersing"],
  ["lamos1b.pl", "seeds_produced*element([dispersability],index(1))"],
  ["lamos1b.pl", "sum([c]*[numbers])"],
  ["lamos1b.pl", "sum([number]*[fuel_per_indiv])"],
  ["lamos1b.pl", "sum([water_use]*[number])"],
  ["lamos1b.pl", "sum({interflow_0})"],
  ["lamos1b.pl", "sum({interflow})"],
  ["lamos1b.pl", "water"],
  ["landuse1a.pl", "(! (column==column_0 and row==row_0)and abs(column-column_0)<1.5 and abs(row-row_0)<1.5)"],
  ["landuse1a.pl", "(if change_to_crop==1 then 1/dt(1)elseif change_to_forest==1 then-1/dt(1)else 0)"],
  ["landuse1a.pl", "(if column==1 then 2 else 1)"],
  ["landuse1a.pl", "(if state==1 and sum({volume})>rand_var(250,400)and n_crop_neighbour>1.9 then 1 else 0)"],
  ["landuse1a.pl", "(if state==1 and(sum({volume})>250 and n_crop_neighbour>=2 and rand_var(0,1)<0.4)or column==1 and sum({volume})>350 and time(1)>0 or n_crop_neighbour>6 then 1 else 0)"],
  ["landuse1a.pl", "(if state==2 and sum({time_under_crop})>100 then 1 else 0)"],
  ["landuse1a.pl", "(if state==2 and sum({time_under_crop})>20 then 1 else 0)"],
  ["landuse1a.pl", "(if state==2 then 0 else sum({volume})/450+1)"],
  ["landuse1a.pl", "(if state==2 then 1 else 0)"],
  ["landuse1a.pl", "(if time(1)<1 then maxvol else rand_const(0,50))"],
  ["landuse1a.pl", "(state==1)"],
  ["landuse1a.pl", "(state==2)"],
  ["landuse1a.pl", "0"],
  ["landuse1a.pl", "0.03*volume*(1-volume/maxvol)"],
  ["landuse1a.pl", "0.5*(1-biomass/20)"],
  ["landuse1a.pl", "1"],
  ["landuse1a.pl", "floor((index(1)-1)/15)+1"],
  ["landuse1a.pl", "fmod(index(1)-1,15)+1"],
  ["landuse1a.pl", "rand_const(0,5)"],
  ["landuse1a.pl", "rand_const(350,450)"],
  ["landuse1a.pl", "sum({biomass})"],
  ["landuse1a.pl", "sum({crop_neighbour_0})"],
  ["landuse1a.pl", "sum({time_under_crop})"],
  ["landuse1a.pl", "sum({volume})"],
  ["landuse1b.pl", "(! (column==column_0 and row==row_0)and abs(column-column_0)<1.5 and abs(row-row_0)<1.5)"],
  ["landuse1b.pl", "(if change_to_crop==1 then 1/dt(1)elseif change_to_forest==1 then-1/dt(1)else 0)"],
  ["landuse1b.pl", "(if column==1 then 2 else 1)"],
  ["landuse1b.pl", "(if state==1 and sum({volume})>rand_var(250,400)and n_crop_neighbour>1.9 then 1 else 0)"],
  ["landuse1b.pl", "(if state==1 and(sum({volume})>250 and n_crop_neighbour>=2 and rand_var(0,1)<0.4)or column==1 and sum({volume})>350 and time(1)>0 or n_crop_neighbour>6 then 1 else 0)"],
  ["landuse1b.pl", "(if state==2 and sum({time_under_crop})>100 then 1 else 0)"],
  ["landuse1b.pl", "(if state==2 and sum({time_under_crop})>20 then 1 else 0)"],
  ["landuse1b.pl", "(if state==2 then 0 else sum({volume})/450+1)"],
  ["landuse1b.pl", "(if state==2 then 1 else 0)"],
  ["landuse1b.pl", "(if time(1)<1 then maxvol else rand_const(0,50))"],
  ["landuse1b.pl", "(state==1)"],
  ["landuse1b.pl", "(state==2)"],
  ["landuse1b.pl", "0"],
  ["landuse1b.pl", "0.03*volume*(1-volume/maxvol)"],
  ["landuse1b.pl", "0.5*(1-biomass/20)"],
  ["landuse1b.pl", "1"],
  ["landuse1b.pl", "floor((index(1)-1)/40)+1"],
  ["landuse1b.pl", "fmod(index(1)-1,40)+1"],
  ["landuse1b.pl", "rand_const(0,5)"],
  ["landuse1b.pl", "rand_const(350,450)"],
  ["landuse1b.pl", "sum({biomass})"],
  ["landuse1b.pl", "sum({crop_neighbour_0})"],
  ["landuse1b.pl", "sum({time_under_crop})"],
  ["landuse1b.pl", "sum({volume})"],
  ["life_input.pl", "'\"false\"'"],
  ["life_input.pl", "(editor_row-1)*editor_width+editor_column"],
  ["life_input.pl", "(editor_row>0,editor_row<=editor_height,editor_column>0,editor_column<=editor_width)", 1],
  ["life_input.pl", "(if time('')==0 then starts_alive else last(prev(0) and live_neighbours==2 or live_neighbours==3))"],
  ["life_input.pl", "(if use_editor then element([alive],square_for_value) else '\"false\"')"],
  ["life_input.pl", "(neighbours_columns>=0,neighbours_columns<width,neighbours_rows>=0,neighbours_rows<height)", 1],
  ["life_input.pl", "[column,column-1,column-1,column]"],
  ["life_input.pl", "[row,row,row-1,row-1]"],
  ["life_input.pl", "20"],
  ["life_input.pl", "200"],
  ["life_input.pl", "40000/width"],
  ["life_input.pl", "any(index(1) is {neighbours_ids_env})"],
  ["life_input.pl", "ceil(index(1)/editor_height)"],
  ["life_input.pl", "column-floor((width-editor_width)/2)"],
  ["life_input.pl", "column+element([-1,0,1,-1,1,-1,0,1],index(1))"],
  ["life_input.pl", "index(1)"],
  ["life_input.pl", "index(1)-editor_width*(row-1)"],
  ["life_input.pl", "int((my_id-1)/width)"],
  ["life_input.pl", "int(fmod(my_id-1,width))"],
  ["life_input.pl", "live_env"],
  ["life_input.pl", "row-floor((height-editor_height)/2)"],
  ["life_input.pl", "row+element([-1,-1,-1,0,0,1,1,1],index(1))"],
  ["life_input.pl", "sum(if {live_test} then 1 else 0)"],
  ["life_input.pl", "width*neighbours_rows+neighbours_columns+1"],
  ["markov1.pl", "(if time(1)==0 then 0 elseif prev(1)==0 and rand_var(0,1)< 0.1 then 1 elseif prev(1)==1 and rand_var(0,1)< 0.1 then 0 else prev(1))"],
  ["markov1.pl", "1"],
  ["markov1.pl", "fmod(index(1)-1,10)+1"],
  ["markov1.pl", "sum([state])"],
  ["markov2.pl", " -state+sum([select])"],
  ["markov2.pl", "(if r>[low] and r<[up] then [index] else 0)"],
  ["markov2.pl", "[[ 0.0, 0.96, 0.98],[ 0.0, 0.02, 0.98],[ 0.0, 0.02, 0.04]]"],
  ["markov2.pl", "[[ 0.96, 0.98, 1.0],[ 0.02, 0.98, 1.0],[ 0.02, 0.04, 1.0]]"],
  ["markov2.pl", "[1,2,3]"],
  ["markov2.pl", "1"],
  ["markov2.pl", "element([[lower]],state)"],
  ["markov2.pl", "element([[upper]],state)"],
  ["markov2.pl", "floor((index(1)-1)/20)+1"],
  ["markov2.pl", "fmod(index(1)-1,20)+1"],
  ["markov2.pl", "rand_var(0,1)"],
  ["Mod1-1aP.pl", " - ('Vflask'*(exp(- ('Finout'*time(0)+const)/'Vflask')-'Cin'))"],
  ["Mod1-1aP.pl", " - (log('Cin'-'Wsalt_init'/'Vflask')*'Vflask')"],
  ["Mod1-1aP.pl", "'Cflask'*'Finout'"],
  ["Mod1-1aP.pl", "'Cin'*'Fin'"],
  ["Mod1-1aP.pl", "'Wsalt_init'"],
  ["Mod1-1aP.pl", "'Wsalt'/'Vflask'"],
  ["Mod1-1aP.pl", "2"],
  ["Mod1-1aP.pl", "30"],
  ["Mod1-1aP.pl", "5"],
  ["Mod1-1bP.pl", " - ('Vflask'*(exp(- ('Finout'*time(0)+const)/'Vflask')-'Cin'))"],
  ["Mod1-1bP.pl", " - (log('Cin'-'Wsalt_init'/'Vflask')*'Vflask')"],
  ["Mod1-1bP.pl", "'Cflask'*'Finout'"],
  ["Mod1-1bP.pl", "'Cin'*'Vflask'"],
  ["Mod1-1bP.pl", "'Fin_out'*cin_water"],
  ["Mod1-1bP.pl", "'Wsalt_init'"],
  ["Mod1-1bP.pl", "'Wsalt'/'Vflask'"],
  ["Mod1-1bP.pl", "'Wsalt1_init'"],
  ["Mod1-1bP.pl", "'Wsalt1'/'Vflask'*'Fin_out'"],
  ["Mod1-1bP.pl", "10"],
  ["Mod1-1bP.pl", "2"],
  ["Mod1-1bP.pl", "30"],
  ["Mod1-1bP.pl", "5"],
  ["modmed1.pl", " 0.1"],
  ["modmed1.pl", " 0.1 *leaf"],
  ["modmed1.pl", " 0.1 *roots"],
  ["modmed1.pl", "(if (fire==1,leaf>0) then leaf/dt(1) else 0)", 1],
  ["modmed1.pl", "(if (fire==1,stem>0) then stem/dt(1) else 0)", 1],
  ["modmed1.pl", "(if (time(1)>0,rand(0,1)< 0.0) then 1 else 0)", 1],
  ["modmed1.pl", "(if leaf>0 then  0.01*goats else 0)"],
  ["modmed1.pl", "(if water>0 then  0.1*sum([leaf]) else 0)"],
  ["modmed1.pl", "(if water>20 then  0.2*(water-20) else 0)"],
  ["modmed1.pl", "0"],
  ["modmed1.pl", "1"],
  ["modmed1.pl", "element([ 0.4, 0.5, 0.6, 0.7, 0.8],index(1))*leaf*(1-leaf/2)*graph(season)"],
  ["modmed1.pl", "floor(fmod(time(1),50))"],
  ["modmed1.pl", "graph(season)"],
  ["Molusc_june06.pl", " 0.0"],
  ["Molusc_june06.pl", " 0.0005"],
  ["Molusc_june06.pl", " 0.005"],
  ["Molusc_june06.pl", " 0.007"],
  ["Molusc_june06.pl", " 0.01"],
  ["Molusc_june06.pl", " 0.013"],
  ["Molusc_june06.pl", " 0.015"],
  ["Molusc_june06.pl", " 0.017"],
  ["Molusc_june06.pl", " 0.0958"],
  ["Molusc_june06.pl", " 0.5"],
  ["Molusc_june06.pl", " 0.614"],
  ["Molusc_june06.pl", " 0.756"],
  ["Molusc_june06.pl", " 0.9271200000000001"],
  ["Molusc_june06.pl", " 1.19"],
  ["Molusc_june06.pl", " 18.1"],
  ["Molusc_june06.pl", " 2.5"],
  ["Molusc_june06.pl", " 7.17"],
  ["Molusc_june06.pl", " 73.54000000000001"],
  ["Molusc_june06.pl", "'Actual_yield_2000'/'Actual_Yield'"],
  ["Molusc_june06.pl", "'Agriculture_to_keep_outside_protected_areas'*proportion_FC"],
  ["Molusc_june06.pl", "'Agriculture_to_keep_outside_protected_areas'*proportion_GFC"],
  ["Molusc_june06.pl", "'Agriculture_to_keep_outside_protected_areas'*proportion_PC"],
  ["Molusc_june06.pl", "'Demand_ratio'*'Productivity_ratio_2005'*'Oversupply_ratio'"],
  ["Molusc_june06.pl", "'Demand_ratio'*'Productivity_ratio_2005'*oversupply_ratio"],
  ["Molusc_june06.pl", "'Dens_reg'*surface"],
  ["Molusc_june06.pl", "'FC_abs'-'FC_surface_abs_ite2'"],
  ["Molusc_june06.pl", "'FC_abs'/surface"],
  ["Molusc_june06.pl", "'FC_adjusted'-modifiable_surface+modifiable_surface*'Change_coefficient'"],
  ["Molusc_june06.pl", "'FC_surface_abs_ite1'-modifiable_surface_bis+modifiable_surface_bis*'Change_coef_bis'"],
  ["Molusc_june06.pl", "'Food_crops_ini_rel'*surface"],
  ["Molusc_june06.pl", "'GFC_abs'-'GFC_surface_abs_ite2'"],
  ["Molusc_june06.pl", "'GFC_abs'/surface"],
  ["Molusc_june06.pl", "'GFC_adjusted'-modifiable_surface+modifiable_surface*'Change_coefficient'"],
  ["Molusc_june06.pl", "'GFC_ini_abs_link_3'"],
  ["Molusc_june06.pl", "'GFC_ini_abs'"],
  ["Molusc_june06.pl", "'GFC_ini_rel'*surface"],
  ["Molusc_june06.pl", "'GFC_surface_abs_ite1'-modifiable_surface_bis+modifiable_surface_bis*change_coef_bis"],
  ["Molusc_june06.pl", "'K'*surface"],
  ["Molusc_june06.pl", "'LPJ_data'"],
  ["Molusc_june06.pl", "'NW_area'-removed_NW"],
  ["Molusc_june06.pl", "'NW_area'/surface"],
  ["Molusc_june06.pl", "'NW_max_to_remove'-'NW_to_remove'"],
  ["Molusc_june06.pl", "'NW_to_remove'/dt('')"],
  ["Molusc_june06.pl", "'PC_abs'-'PC_surface_abs_ite2'"],
  ["Molusc_june06.pl", "'PC_abs'/surface"],
  ["Molusc_june06.pl", "'PC_adjusted'-modifiable_surface+modifiable_surface*'Change_coefficient'"],
  ["Molusc_june06.pl", "'PC_ini_abs_link_4'"],
  ["Molusc_june06.pl", "'PC_ini_abs'"],
  ["Molusc_june06.pl", "'PC_surface_abs_ite1'-modifiable_surface_bis+modifiable_surface_bis*change_coef_bis"],
  ["Molusc_june06.pl", "'Potential_with_technology'*max('Scaling_factor'-'Management_factor_plus',0)"],
  ["Molusc_june06.pl", "'Predicted_actual_yield'*'GFC_surf_ini'"],
  ["Molusc_june06.pl", "'Predicted_actual_yield'*'PC_surf_ini'"],
  ["Molusc_june06.pl", "'Productivity_ratio_2000'/ratio_2005_2000"],
  ["Molusc_june06.pl", "'Productivity_ratio_2000'+(1-'Productivity_ratio_2000')/6"],
  ["Molusc_june06.pl", "'Suitability_index_Link'"],
  ["Molusc_june06.pl", "'Surface_change'*'GFC_ini_abs'"],
  ["Molusc_june06.pl", "'Surface_change'*'PC_ini_abs'"],
  ["Molusc_june06.pl", "'Surface_change'*food_crops_ini_abs"],
  ["Molusc_june06.pl", "'Urb_dens'+inland_waters_0+sea_dens+pro_forest+pro_land+max(pro_pcrop+pro_crop+pro_grass,'Agro_threshold')"],
  ["Molusc_june06.pl", "'Urb_reg'-'Urb_Model'"],
  ["Molusc_june06.pl", "('Urb_dens'+inland_waters+sea_dens+pro_forest+pro_land)*surface+'FC_abs'+'GFC_abs'+'PC_abs'"],
  ["Molusc_june06.pl", "(countryID_link=='CountryID')"],
  ["Molusc_june06.pl", "(if 'Altitude_mask'==1 then 0 else remaining_surplus_3-woody_growth*dt('')+'Woody_decline'*dt(''))"],
  ["Molusc_june06.pl", "(if 'Altitude_mask'==1 then 0 elseif surface-('FC_surface_rel'+'GFC_surface_rel'+'PC_surface_rel'+'Urb_dens'+pro_land+liquid_rel+non_woody_rel+woody_rel+sea_dens+inland_waters+'Forest_rel')*surface<0 then 0 else surface-('FC_surface_rel'+'GFC_surface_rel'+'PC_surface_rel'+'Urb_dens'+pro_land+liquid_rel+non_woody_rel+woody_rel+sea_dens+inland_waters+'Forest_rel')*surface)"],
  ["Molusc_june06.pl", "(if 'Change_coefficient' '!=' 0 then 0 else 'Expected_change_abs'-('Surface_where_changes_apply'-'Temp_GFC_surface'))"],
  ["Molusc_june06.pl", "(if 'Change_coefficient' '!=' 0 then 0 else 'Expected_change_abs'-('Surface_where_changes_apply'-'Temp_PC_surface'))"],
  ["Molusc_june06.pl", "(if 'Change_coefficient' '!=' 0 then 0 else 'Expected_change'-('Surface_where_changes_apply'-'Temp_FC_surface'))"],
  ["Molusc_june06.pl", "(if 'FC_abs'-protected_abs_FC<0 then 'FC_abs' else('FC_abs'-protected_abs_FC)*coef_remove_0+protected_abs_FC)"],
  ["Molusc_june06.pl", "(if 'FC_abs'+'GFC_abs'+'PC_abs'<=0 then 0 else 'FC_abs'/('FC_abs'+'GFC_abs'+'PC_abs'))"],
  ["Molusc_june06.pl", "(if 'FC_abs'+'GFC_abs'+'PC_abs'<=0 then 0 else 'GFC_abs'/('FC_abs'+'GFC_abs'+'PC_abs'))"],
  ["Molusc_june06.pl", "(if 'FC_abs'+'GFC_abs'+'PC_abs'<=0 then 0 else 'PC_abs'/('FC_abs'+'GFC_abs'+'PC_abs'))"],
  ["Molusc_june06.pl", "(if 'Food_crops_abs_adjusted'-'FC_surf_expected'<0 then 0 else('Food_crops_abs_adjusted'-'FC_surf_expected')*dt(''))"],
  ["Molusc_june06.pl", "(if 'GFC_abs_adjusted'-'GFC_surf_expected'<0 then 0 else('GFC_abs_adjusted'-'GFC_surf_expected')*dt(''))"],
  ["Molusc_june06.pl", "(if 'GFC_abs'-protected_abs_GFC<0 then 'GFC_abs' else('GFC_abs'-protected_abs_GFC)*coef_remove_0+protected_abs_GFC)"],
  ["Molusc_june06.pl", "(if 'High_risks_floodable_areas'==1 then 0 elseif 'Medium_risks_floodable_areas'==1 then 0 elseif 'Food_crops_ini_rel'-'FC_surface_rel'<0 then 0 else 'Food_crops_ini_rel'-'FC_surface_rel')"],
  ["Molusc_june06.pl", "(if 'High_risks_floodable_areas'==1 then 0 elseif 'Medium_risks_floodable_areas'==1 then 0 elseif 'GFC_ini_rel'-'GFC_surface_rel'<0 then 0 else 'GFC_ini_rel'-'GFC_surface_rel')"],
  ["Molusc_june06.pl", "(if 'High_risks_floodable_areas'==1 then 0 elseif 'Medium_risks_floodable_areas'==1 then 0 elseif 'PC_ini_rel'-'PC_surface_rel'<0 then 0 else 'PC_ini_rel'-'PC_surface_rel')"],
  ["Molusc_june06.pl", "(if 'IDNUTS'==999 or 'IDNUTS'==998 then 0 else element([suittot],'IDNUTS'))"],
  ["Molusc_june06.pl", "(if 'IDNUTS'==999 or 'IDNUTS'==998 then 0 elseif espace>=1 then 0 elseif random>=1 then 0 elseif 'Dist_to_roads'>dist_to_roads_threshold then 0 elseif 'Dist_to_large_cities'<dist_to_large_threshold then pds_large*surface*flood_coefficient elseif 'Dist_to_medium_cities'<dist_to_med_threshold then pds_med*surface*flood_coefficient elseif 'Dist_to_small_cities'<dist_to_sm_threshold then pds_small*surface*flood_coefficient elseif rural==1 then pds_rural*surface*flood_coefficient else 0)"],
  ["Molusc_june06.pl", "(if 'IDNUTS'==999 then 0 else element([diff_pond],'IDNUTS'))"],
  ["Molusc_june06.pl", "(if 'IDNUTS'==999 then 0 elseif 'IDNUTS'==998 then 0 else element([employment_in_agriculture],'IDNUTS'))"],
  ["Molusc_june06.pl", "(if 'NW_area'-'NW_max_to_remove'<0 then 'NW_area' else 'NW_max_to_remove')"],
  ["Molusc_june06.pl", "(if 'PC_abs_adjusted'-'PC_surf_expected'<0 then 0 else('PC_abs_adjusted'-'PC_surf_expected')*dt(''))"],
  ["Molusc_june06.pl", "(if 'PC_abs'-protected_abs_PC<0 then 'PC_abs' else('PC_abs'-protected_abs_PC)*coef_remove_0+protected_abs_PC)"],
  ["Molusc_june06.pl", "(if 'Surface_where_changes_apply'>'Expected_change_0' then('Surface_where_changes_apply'-'Expected_change_0')/'Surface_where_changes_apply' else 0)"],
  ["Molusc_june06.pl", "(if 'Surface_where_changes_apply'>'Expected_change_abs' then('Surface_where_changes_apply'-'Expected_change_abs')/'Surface_where_changes_apply' else 0)"],
  ["Molusc_june06.pl", "(if dens_add_woody<=0 then 0 elseif remaining_woody_rent_area<0 then 0 else dens_add_woody*remaining_woody_rent_area)"],
  ["Molusc_june06.pl", "(if diff_FC<0 then 0 else diff_FC/dt(''))"],
  ["Molusc_june06.pl", "(if diff_GFC<0 then 0 else diff_GFC/dt(''))"],
  ["Molusc_june06.pl", "(if diff_PC<0 then 0 else diff_PC/dt(''))"],
  ["Molusc_june06.pl", "(if diff<var_max then diff else var_max)"],
  ["Molusc_june06.pl", "(if forest_change>sum({remaining_surplus__})then sum({remaining_surplus__})else forest_change)"],
  ["Molusc_june06.pl", "(if forest_max_to_remove>forest_area_in_surplus then forest_area_in_surplus else forest_max_to_remove)"],
  ["Molusc_june06.pl", "(if index(1)==1 then 'Actual_yield_wheat_2000' elseif index(1)==2 then 'Actual_yield_maize_2000' elseif index(1)==3 then 'Actual_yield_sunflower_2000' else 'Actual_yield_soya_2000')"],
  ["Molusc_june06.pl", "(if index(1)==1 then scaling_factor_wheat elseif index(1)==2 then scaling_factor_maize elseif index(1)==3 then scaling_factor_sunflower else scaling_factor_soya)"],
  ["Molusc_june06.pl", "(if index(1)==1 then weight_wheat*'Predicted_actual_yield' elseif index(1)==2 then weight_maize*'Predicted_actual_yield' elseif index(1)==3 then weight_sunflower*'Predicted_actual_yield' else weight_soy*'Predicted_actual_yield')"],
  ["Molusc_june06.pl", "(if index(1)==1 then weight_wheat*actual_yield_2000 elseif index(1)==2 then weight_maize*actual_yield_2000 elseif index(1)==3 then weight_sunflower*actual_yield_2000 else weight_soy*actual_yield_2000)"],
  ["Molusc_june06.pl", "(if index(1)==1 then(if time('')<5 then 'LPJ_data_wheat' elseif time('')<30 then 'LPJ_data_wheat_2011_2030' elseif time('')<50 then 'LPJ_data_wheat_2031_2050' else 'LPJ_data_wheat_2051_2070')elseif index(1)==2 then(if time('')<5 then 'LPJ_data_maize_2000_2010' elseif time('')<30 then 'LPJ_data_maize_2011_2030' elseif time('')<50 then 'LPJ_data_maize_2031_2050' else 'LPJ_data_maize_2051_2070')elseif index(1)==3 then(if time('')<5 then 'LPJ_data_sunflower' elseif time('')<30 then 'LPJ_data_sunflower_2011_2030' elseif time('')<50 then 'LPJ_data_sunflower_2031_2050' else 'LPJ_data_sunflower_2051_2070')else(if time('')<5 then 'LPJ_data_soya' elseif time('')<35 then 'LPJ_data_soya_2011_2030' elseif time('')<50 then 'LPJ_data_soya_2031_2050' else 'LPJ_data_soya_2051_2070'))"],
  ["Molusc_june06.pl", "(if inland_waters+sea_dens+'Urb_dens'+'FC_surface_rel'+'GFC_surface_rel'+'PC_surface_rel'+pro_land+liquid_rel+non_woody_rel+woody_rel+'Forest_rel'<=1 then 0 else abs(surface-(inland_waters+sea_dens+'Urb_dens'+'FC_surface_rel'+'GFC_surface_rel'+'PC_surface_rel'+pro_land+liquid_rel+non_woody_rel+woody_rel+'Forest_rel')*surface))"],
  ["Molusc_june06.pl", "(if liquid_area-liquid_max_to_remove<0 then liquid_area else liquid_max_to_remove)"],
  ["Molusc_june06.pl", "(if pro_land+sea_dens+inland_waters+pro_forest+'GFC_surface_rel'+'PC_surface_rel'+'FC_surface_rel'+'Urb_dens'>=1 then 0 else min(surplus_ini_2005_abs+surface*(surplus_foodcrops+surplus_grassland+surplus_PC),surface*(1-pro_land+sea_dens+inland_waters+pro_forest+'GFC_surface_rel'+'PC_surface_rel'+'FC_surface_rel'+'Urb_dens')))"],
  ["Molusc_june06.pl", "(if protected_abs_FC+protected_abs_GFC+protected_abs_PC>='Agro_threshold'*surface then 0 else 'Agro_threshold'*surface-(protected_abs_FC+protected_abs_GFC+protected_abs_PC))"],
  ["Molusc_june06.pl", "(if remaining_liquid_rent_area<0 then 0 else dens_add_liquid*remaining_liquid_rent_area)"],
  ["Molusc_june06.pl", "(if remaining_NW_rent_area<0 then 0 else dens_add_NW*remaining_NW_rent_area)"],
  ["Molusc_june06.pl", "(if remaining_rent_area_liquid<=0 then 0 elseif remaining_rent_area_liquid<'Liquid_change' then 1 else 'Liquid_change'/remaining_rent_area_liquid)"],
  ["Molusc_june06.pl", "(if remaining_rent_area_non_woody<=0 then 0 elseif remaining_rent_area_non_woody<'NW_change' then 1 else 'NW_change'/remaining_rent_area_non_woody)"],
  ["Molusc_june06.pl", "(if remaining_rent_area_woody<=0 then 0 elseif remaining_rent_area_woody<woody_change then 1 else woody_change/remaining_rent_area_woody)"],
  ["Molusc_june06.pl", "(if remaining_surplus_2<0 then 0 elseif rentability_non_woody== -1 then 0 elseif rentability_non_woody==0 then 0 else remaining_surplus_2)"],
  ["Molusc_june06.pl", "(if remaining_surplus_3<0 then 0 elseif rentability_woody== -1 then 0 elseif rentability_woody==0 then 0 else remaining_surplus_3)"],
  ["Molusc_june06.pl", "(if remaining_surplus_4_link>0 then remaining_surplus_4_link else 0)"],
  ["Molusc_june06.pl", "(if remaining_surplus_4>0 then forest_change_rate_in_surplus*remaining_surplus_4 else 0)"],
  ["Molusc_june06.pl", "(if remaining_surplus<0 then 0 elseif rentability_liquid== -1 then 0 elseif rentability_liquid==0 then 0 else remaining_surplus)"],
  ["Molusc_june06.pl", "(if remaining_surplus>=0 then 0 else abs(remaining_surplus))"],
  ["Molusc_june06.pl", "(if rent_crop_bis==99999 or rent_crop_bis==999999 then 1 elseif scenario==3 then 1 elseif rent_crop_bis>='FC_rent_thr' then 0 else 1-(rent_crop_bis-rent_min_foodcrops)/('FC_rent_thr'-rent_min_foodcrops)*k_foodcrops)"],
  ["Molusc_june06.pl", "(if rent_grass_bis==99999 or rent_grass_bis==999999 then 1 elseif scenario==3 then 1 elseif rent_grass_bis>='GFC_rent_thr' then 0 else 1-(rent_grass_bis-rent_min_grasslands)/('GFC_rent_thr'-rent_min_grasslands)*k_GFC)"],
  ["Molusc_june06.pl", "(if rent_pcrops_bis==99999 or rent_pcrops_bis==999999 then 1 elseif scenario==3 then 1 elseif rent_pcrops_bis>='PC_rent_thr' then 0 else 1-(rent_pcrops_bis-rent_min_pcrops)/('PC_rent_thr'-rent_min_pcrops)*k_PC)"],
  ["Molusc_june06.pl", "(if rentability_liquid== -1 then 0 elseif rentability_liquid==0 then 0 else surplus_ini_2005_abs)"],
  ["Molusc_june06.pl", "(if rentability_non_woody== -1 then 0 elseif rentability_non_woody==0 then 0 else surplus_ini_2005_abs_2)"],
  ["Molusc_june06.pl", "(if rentability_woody== -1 then 0 elseif rentability_woody==0 then 0 else surplus_ini_2005_abs_3)"],
  ["Molusc_june06.pl", "(if scenario==1 then 0 else(if 'Employment_in_agriculture'>20 then min( 0.12,'Food_crops_ini_rel'+'PC_ini_rel'+'GFC_ini_rel')else min( 0.1,'Food_crops_ini_rel'+'PC_ini_rel'+'GFC_ini_rel')))"],
  ["Molusc_june06.pl", "(if scenario==1 then(if time('')<=10 then 'M_temp'*time('')else 'M_temp'*10)elseif scenario==2 then(if time('')<=10 then 'M_temp'*time('')else 'M_temp'*10)else(if time('')<=10 then 'M_temp'*time('')else 'M_temp'*10))"],
  ["Molusc_june06.pl", "(if scenario==1 then(if time('')<=10 then 'POT_LPJ'*(1+time('')*'T_temp_0')else 'POT_LPJ'*(1+'T_temp_0'*10+'T_temp_0'*(time('')-10)))elseif scenario==2 then(if time('')<=10 then 'POT_LPJ'*(1+time('')*'T_temp_0')else 'POT_LPJ'*(1+'T_temp_0'*10+'T_temp_0'*(time('')-10)))else(if time('')<=10 then 'POT_LPJ'*(1+time('')*'T_temp_0')else 'POT_LPJ'*(1+'T_temp_0'*10+'T_temp_0'*(time('')-10))))"],
  ["Molusc_june06.pl", "(if scenario==1 then(if time('')<=10 then 'POT_LPJ'*(1+time('')*element(['T'],1))else 'POT_LPJ'*(1+element(['T'],1)*10+element(['T'],4)*(time('')-10)))elseif scenario==2 then(if time('')<=10 then 'POT_LPJ'*(1+time('')*element(['T'],2))else 'POT_LPJ'*(1+element(['T'],2)*10+element(['T'],5)*(time('')-10)))else(if time('')<=10 then 'POT_LPJ'*(1+time('')*element(['T'],3))else 'POT_LPJ'*(1+element(['T'],3)*10+element(['T'],6)*(time('')-10))))"],
  ["Molusc_june06.pl", "(if scenario==1 then(if time('')<=10 then element(['M'],1)*time('')else element(['M'],1)*10)elseif scenario==2 then(if time('')<=10 then element(['M'],2)*time('')else element(['M'],2)*10)else(if time('')<=10 then element(['M'],3)*time('')else element(['M'],3)*10))"],
  ["Molusc_june06.pl", "(if scenario==2 or scenario==3 then 'FC_surface_abs_ite1'-protected_abs-area_to_keep_FC elseif rent_crop_bis>='FC_rent_thr' then 0 else 'FC_surface_abs_ite1'-protected_abs-area_to_keep_FC)"],
  ["Molusc_june06.pl", "(if scenario==2 or scenario==3 then 'GFC_surface_abs_ite1'-protected_abs-area_to_keep_GFC elseif rent_grass_bis>='GFC_rent_thr' then 0 else 'GFC_surface_abs_ite1'-protected_abs-area_to_keep_GFC)"],
  ["Molusc_june06.pl", "(if scenario==2 or scenario==3 then 'PC_surface_abs_ite1'-protected_abs-area_to_keep_PC elseif rent_pcrops_bis>='PC_rent_thr' then 0 else 'PC_surface_abs_ite1'-protected_abs-area_to_keep_PC)"],
  ["Molusc_june06.pl", "(if suittot==0 then 0 else 'Suitability_index'/suittot)"],
  ["Molusc_june06.pl", "(if sum({remaining_surplus__})==0 then 0 else forest_change_in_surplus/sum({remaining_surplus__}))"],
  ["Molusc_june06.pl", "(if sum({space_remaining})==0 then 0 elseif sum({space_remaining})<forest_change_outside_surplus then 1 else forest_change_outside_surplus/sum({space_remaining}))"],
  ["Molusc_june06.pl", "(if surf_where_ch_apply_bis>exp_change_bis then(surf_where_ch_apply_bis-exp_change_bis)/surf_where_ch_apply_bis else 0)"],
  ["Molusc_june06.pl", "(if time('')<=20 then(if 'CountryID'==2 or 'CountryID'==10 or 'CountryID'==22 or 'CountryID'==26 or 'CountryID'==3 or 'CountryID'==18 or 'CountryID'==23 or 'CountryID'==13 or 'CountryID'==16 or 'CountryID'==25 or 'CountryID'==8 then sum({forest_ini_abs})+sum({forest_ini_abs})* 0.0005*(time('')+1)elseif 'CountryID'==12 or 'CountryID'==6 then sum({forest_ini_abs})+sum({forest_ini_abs})* 0.00025*(time('')+1)elseif 'CountryID'==7 or 'CountryID'==15 or 'CountryID'==4 or 'CountryID'==30 then sum({forest_ini_abs})+sum({forest_ini_abs})* 0.001*(time('')+1)elseif 'CountryID'==14 or 'CountryID'==5 then sum({forest_ini_abs})+sum({forest_ini_abs})* 0.0005*(time('')+1)elseif 'CountryID'==8 or 'CountryID'==17 or 'CountryID'==24 or 'CountryID'==28 then sum({forest_ini_abs})+sum({forest_ini_abs})* 0.0003*(time('')+1)elseif 'CountryID'==17 or 'CountryID'==27 then sum({forest_ini_abs})+sum({forest_ini_abs})* 0.0001*(time('')+1)else sum({forest_ini_abs}))else(if 'CountryID'==2 or 'CountryID'==10 or 'CountryID'==22 or 'CountryID'==26 then sum({forest_ini_abs})+sum({forest_ini_abs})* 0.0003*(time('')+1)elseif 'CountryID'==12 or 'CountryID'==6 or 'CountryID'==13 or 'CountryID'==16 or 'CountryID'==25 or 'CountryID'==8 then sum({forest_ini_abs})+sum({forest_ini_abs})* -0.007*(time('')+1)elseif 'CountryID'==7 or 'CountryID'==15 or 'CountryID'==4 or 'CountryID'==30 or 'CountryID'==3 or 'CountryID'==23 or 'CountryID'==18 then sum({forest_ini_abs})+sum({forest_ini_abs})* -0.0003*(time('')+1)elseif 'CountryID'==14 or 'CountryID'==5 then sum({forest_ini_abs})+sum({forest_ini_abs})* 0.0003*(time('')+1)elseif 'CountryID'==8 or 'CountryID'==17 or 'CountryID'==24 or 'CountryID'==28 then sum({forest_ini_abs})+sum({forest_ini_abs})* 0.0003*(time('')+1)elseif 'CountryID'==17 or 'CountryID'==27 then sum({forest_ini_abs})+sum({forest_ini_abs})* 0.0003*(time('')+1)else sum({forest_ini_abs})))"],
  ["Molusc_june06.pl", "(if time('')<=25 then(if 'High_risks_floodable_areas'==1 then rent_min_foodcrops elseif 'Medium_risks_floodable_areas'==1 then rent_min_foodcrops else rent_crop_2000_2030)elseif time('')<=55 then(if 'High_risks_floodable_areas'==1 then rent_min_foodcrops elseif 'Medium_risks_floodable_areas'==1 then rent_min_foodcrops else rent_crop_2031_2060)else(if 'High_risks_floodable_areas'==1 then rent_min_foodcrops elseif 'Medium_risks_floodable_areas'==1 then rent_min_foodcrops else rent_crop_2060_2080))"],
  ["Molusc_june06.pl", "(if time('')<=25 then(if 'High_risks_floodable_areas'==1 then rent_min_grasslands elseif 'Medium_risks_floodable_areas'==1 then rent_min_grasslands else rent_grass_2000_2030)elseif time('')<=55 then(if 'High_risks_floodable_areas'==1 then rent_min_grasslands elseif 'Medium_risks_floodable_areas'==1 then rent_min_grasslands else rent_grass_2031_2060)else(if 'High_risks_floodable_areas'==1 then rent_min_grasslands elseif 'Medium_risks_floodable_areas'==1 then rent_min_grasslands else rent_grass_2061_2080))"],
  ["Molusc_june06.pl", "(if time('')<=25 then(if 'High_risks_floodable_areas'==1 then rent_min_pcrops elseif 'Medium_risks_floodable_areas'==1 then rent_min_pcrops else rent_pcrops_2000_2030)elseif time('')<=55 then(if 'High_risks_floodable_areas'==1 then rent_min_pcrops elseif 'Medium_risks_floodable_areas'==1 then rent_min_pcrops else rent_pcrops_2031_2060)else(if 'High_risks_floodable_areas'==1 then rent_min_pcrops elseif 'Medium_risks_floodable_areas'==1 then rent_min_pcrops else rent_pcrops_2061_2080))"],
  ["Molusc_june06.pl", "(if time('')<=5 then least([rent_crop_2000_2030])elseif time('')<=25 then least([rent_crop_2031_2060])else least([rent_crop_2060_2080]))"],
  ["Molusc_june06.pl", "(if time('')<=5 then least([rent_grass])elseif time('')<=25 then least([rent_grass_2031_2060])else least([rent_grass_2061_2080]))"],
  ["Molusc_june06.pl", "(if time('')<=5 then least([rent_pcrops_2000_2030])elseif time('')<=25 then least([rent_pcrops_2031_2060])else least([rent_pcrops_2061_2080]))"],
  ["Molusc_june06.pl", "(if time('')<10 then 1 elseif 'High_risks_floodable_areas'==0 then 1 else flood_sensitivity)"],
  ["Molusc_june06.pl", "(if time('')<5 then 'LPJ_data' elseif time('')<25 then 'LPJ_data_2011_2030' else 'LPJ_data_2031_2050')"],
  ["Molusc_june06.pl", "(if time('')<71 then element(['GDP_Matrice'],time('')+7)+(element(['GDP_Matrice'],time('')+8)-element(['GDP_Matrice'],time('')+7))*(time('')-int(time('')))else element(['GDP_Matrice'],81))"],
  ["Molusc_june06.pl", "(if time('')<71 then element(['POP_Matrice'],time('')+7)+(element(['POP_Matrice'],time('')+8)-element(['POP_Matrice'],time('')+7))*(time('')-int(time('')))else element(['POP_Matrice'],51))"],
  ["Molusc_june06.pl", "(if time('')<71 then(element([liquid_data],time('')+2)+(element([liquid_data],time('')+3)-element([liquid_data],time('')+2))*(time('')-int(time(''))))*surface else element([liquid_data],76)*surface)"],
  ["Molusc_june06.pl", "(if time('')<75 then element(['Demand_data'],time('')+2)+(element(['Demand_data'],time('')+3)-element(['Demand_data'],time('')+2))*(time('')-int(time('')))else element(['Demand_data'],76))"],
  ["Molusc_june06.pl", "(if time('')<75 then element(['Oversupply_data'],time('')+2)+(element(['Oversupply_data'],time('')+3)-element(['Oversupply_data'],time('')+2))*(time('')-int(time('')))else element(['Oversupply_data'],76))"],
  ["Molusc_june06.pl", "(if time('')<75 then(element(['NW_data'],time('')+2)+(element(['NW_data'],time('')+3)-element(['NW_data'],time('')+2))*(time('')-int(time(''))))*surface else element(['NW_data'],76)*surface)"],
  ["Molusc_june06.pl", "(if time('')<75 then(element(['Woody_data'],time('')+2)+(element(['Woody_data'],time('')+3)-element(['Woody_data'],time('')+2))*(time('')-int(time(''))))*surface else element(['Woody_data'],76)*surface)"],
  ["Molusc_june06.pl", "(if to_remove==0 then 1 elseif max('FC_abs'-pro_crop*surface,0)+max('PC_abs'-pro_pcrop*surface,0)+max('GFC_abs'-pro_grass*surface,0)==0 then 1 elseif(max('FC_abs'-pro_crop*surface,0)+max('PC_abs'-pro_pcrop*surface,0)+max('GFC_abs'-pro_grass*surface,0)-to_remove)/(max('FC_abs'-pro_crop*surface,0)+max('PC_abs'-pro_pcrop*surface,0)+max('GFC_abs'-pro_grass*surface,0))<0 then 0 else(max('FC_abs'-pro_crop*surface,0)+max('PC_abs'-pro_pcrop*surface,0)+max('GFC_abs'-pro_grass*surface,0)-to_remove)/(max('FC_abs'-pro_crop*surface,0)+max('PC_abs'-pro_pcrop*surface,0)+max('GFC_abs'-pro_grass*surface,0)))"],
  ["Molusc_june06.pl", "(if tot_occupied_area<=surface then 0 else tot_occupied_area-surface)"],
  ["Molusc_june06.pl", "(if tot_rent_area_liquid_2005<=0 then 0 elseif tot_rent_area_liquid_2005<liquid_biofuels_2005 then 1 else liquid_biofuels_2005/tot_rent_area_liquid_2005)"],
  ["Molusc_june06.pl", "(if tot_rent_area_NW_2005_0<=0 then 0 elseif tot_rent_area_NW_2005_0<'NW_biofuels_2005' then 1 else 'NW_biofuels_2005'/tot_rent_area_NW_2005_0)"],
  ["Molusc_june06.pl", "(if tot_rent_area_woody_2005<=0 then 0 elseif tot_rent_area_woody_2005<woody_biofuels_2005 then 1 else woody_biofuels_2005/tot_rent_area_woody_2005)"],
  ["Molusc_june06.pl", "(if urbdiff<0 then 0 elseif espace>=1 then 0 elseif surface-espace*surface<suitrel*urbdiff then surface-espace*surface else suitrel*urbdiff)"],
  ["Molusc_june06.pl", "(if woody_max_to_remove>woody_area then woody_area else woody_max_to_remove)"],
  ["Molusc_june06.pl", "(index=='IDNUTS_link_3')"],
  ["Molusc_june06.pl", "(index=='IDNUTS_link_4')"],
  ["Molusc_june06.pl", "(index=='IDNUTS_Link')"],
  ["Molusc_june06.pl", "(index=='IDNUTS_link2')"],
  ["Molusc_june06.pl", "['M_GRAS','M_BAMBU','M_SEDG']"],
  ["Molusc_june06.pl", "['T_GRAS____2015','T_BAMBU____2015','T_SEDG____2015','T_GRAS___2015','T_BAMBU___2015','T_SEDG___2015']"],
  ["Molusc_june06.pl", "0"],
  ["Molusc_june06.pl", "actual_yield_2000*'GFC_surf_ini'"],
  ["Molusc_june06.pl", "actual_yield_2000*'PC_surf_ini'"],
  ["Molusc_june06.pl", "const+coef_pop*'POP_t_1'+coef_gdp*'GDP_t_1'"],
  ["Molusc_june06.pl", "dens_liquid_2005*rent_liquid_area_2005"],
  ["Molusc_june06.pl", "dens_woody_2005*rent_woody_area_2005"],
  ["Molusc_june06.pl", "element(['NW_data'],1)*surface"],
  ["Molusc_june06.pl", "element(['Woody_data'],1)*surface"],
  ["Molusc_june06.pl", "element([forest_change_rate_in_surplus],countryID)"],
  ["Molusc_june06.pl", "element([forest_change_rate_outside_surplus],countryID)"],
  ["Molusc_june06.pl", "element([liquid_data],1)*surface"],
  ["Molusc_june06.pl", "food_crops_ini_abs"],
  ["Molusc_june06.pl", "food_crops_ini_abs_link2"],
  ["Molusc_june06.pl", "forest_area_in_surplus+forest_area_outside_surplus"],
  ["Molusc_june06.pl", "forest_change-forest_change_in_surplus"],
  ["Molusc_june06.pl", "forest_expected_t_1-sum({tot_forest})"],
  ["Molusc_june06.pl", "forest_ini_abs"],
  ["Molusc_june06.pl", "forest_ini_abs_link"],
  ["Molusc_june06.pl", "forest_ini_rel*surface"],
  ["Molusc_june06.pl", "forest_max_to_remove-forest_to_remove"],
  ["Molusc_june06.pl", "forest_to_remove_link+forest_decline_outside_surplus_link"],
  ["Molusc_june06.pl", "forest_to_remove/dt('')"],
  ["Molusc_june06.pl", "index(1)"],
  ["Molusc_june06.pl", "liquid_area_0/surface"],
  ["Molusc_june06.pl", "liquid_area-removed_liquid"],
  ["Molusc_june06.pl", "liquid_biofuels_abs_t_1-liquid_area_bis"],
  ["Molusc_june06.pl", "liquid_to_remove/dt('')"],
  ["Molusc_june06.pl", "makearray( 1.0,76)"],
  ["Molusc_june06.pl", "makearray( 1.0,81)"],
  ["Molusc_june06.pl", "min('Max_to_remove',forest_area_outside_surplus)/dt('')"],
  ["Molusc_june06.pl", "min(weight*'FC_adjusted',max('FC_adjusted'-protected_abs_FC-'FC_to_keep_outside_pro_areas',0))"],
  ["Molusc_june06.pl", "min(weight*'GFC_adjusted',max('GFC_adjusted'-protected_abs_GFC-'GFC_to_keep_outside_pro_areas',0))"],
  ["Molusc_june06.pl", "min(weight*'PC_adjusted',max('PC_adjusted'-protected_abs_PC-'PC_to_keep_outside_pro_areas',0))"],
  ["Molusc_june06.pl", "non_woody_biofuels_abs_t_1-'NW_area_bis'"],
  ["Molusc_june06.pl", "protected_rel*surface"],
  ["Molusc_june06.pl", "rand_const(0,1/rand_par)"],
  ["Molusc_june06.pl", "remaining_surplus_2-'NW_growth'*dt('')+'NW_decline'*dt('')"],
  ["Molusc_june06.pl", "remaining_surplus-liquid_growth*dt('')+liquid_decline*dt('')"],
  ["Molusc_june06.pl", "rent_NW_area_2005*dens_non_woody_2005"],
  ["Molusc_june06.pl", "space_remaining_link"],
  ["Molusc_june06.pl", "space_remaining*forest_change_rate_outside_surplus"],
  ["Molusc_june06.pl", "sum(['FC_adjusted'])"],
  ["Molusc_june06.pl", "sum(['FC_surface_abs_ite1'])"],
  ["Molusc_june06.pl", "sum(['GFC_adjusted'])"],
  ["Molusc_june06.pl", "sum(['GFC_ini_abs'])"],
  ["Molusc_june06.pl", "sum(['GFC_surface_abs_ite1'])"],
  ["Molusc_june06.pl", "sum(['NW_area'])"],
  ["Molusc_june06.pl", "sum(['NW_to_remove'])"],
  ["Molusc_june06.pl", "sum(['PC_adjusted'])"],
  ["Molusc_june06.pl", "sum(['PC_ini_abs'])"],
  ["Molusc_june06.pl", "sum(['PC_surface_abs_ite1'])"],
  ["Molusc_june06.pl", "sum(['Weighted_actual_yield'])/sum(['FC_surf_ini'])"],
  ["Molusc_june06.pl", "sum(['Weighted_actual_yield'])/sum(['GFC_surf_ini'])"],
  ["Molusc_june06.pl", "sum(['Weighted_actual_yield'])/sum(['PC_surf_ini'])"],
  ["Molusc_june06.pl", "sum(['Weighted_yield_2000'])*'FC_surf_ini'"],
  ["Molusc_june06.pl", "sum(['Weighted_yield'])*'FC_surf_ini'"],
  ["Molusc_june06.pl", "sum(['Yield_2000_weighted'])/sum(['GFC_surf_ini'])"],
  ["Molusc_june06.pl", "sum(['Yield_2000_weighted'])/sum(['PC_surf_ini'])"],
  ["Molusc_june06.pl", "sum([food_crops_ini_abs])"],
  ["Molusc_june06.pl", "sum([liquid_area_0])"],
  ["Molusc_june06.pl", "sum([liquid_to_remove])"],
  ["Molusc_june06.pl", "sum([modifiable_surface_bis])"],
  ["Molusc_june06.pl", "sum([modifiable_surface])"],
  ["Molusc_june06.pl", "sum([remaining_liquid_rent_area])"],
  ["Molusc_june06.pl", "sum([remaining_NW_rent_area])"],
  ["Molusc_june06.pl", "sum([remaining_woody_rent_area])"],
  ["Molusc_june06.pl", "sum([rent_liquid_area_2005])"],
  ["Molusc_june06.pl", "sum([rent_NW_area_2005])"],
  ["Molusc_june06.pl", "sum([rent_woody_area_2005])"],
  ["Molusc_june06.pl", "sum([woody_area_0])"],
  ["Molusc_june06.pl", "sum([woody_to_remove])"],
  ["Molusc_june06.pl", "sum([yield_2000_weighted])/sum(['FC_surf_ini'])"],
  ["Molusc_june06.pl", "sum({'FC_surf'})"],
  ["Molusc_june06.pl", "sum({'GFC_surf'})"],
  ["Molusc_june06.pl", "sum({'PC_surf'})"],
  ["Molusc_june06.pl", "sum({'Urb_surf'})"],
  ["Molusc_june06.pl", "sum({suit})"],
  ["Molusc_june06.pl", "surface*'PC_ini_rel'"],
  ["Molusc_june06.pl", "surface*protected_crop_rel"],
  ["Molusc_june06.pl", "surface*protected_rel"],
  ["Molusc_june06.pl", "surface*surplus_ini_2005_rel"],
  ["Molusc_june06.pl", "surplus_ini_2005_abs_2-'NW_area'"],
  ["Molusc_june06.pl", "surplus_ini_2005_abs-liquid_area_0"],
  ["Molusc_june06.pl", "surplus-liquid_area_0-'NW_area'-woody_area_0-forest_area_in_surplus"],
  ["Molusc_june06.pl", "tot_forest_abs_link-removed_forest"],
  ["Molusc_june06.pl", "tot_forest_abs/surface"],
  ["Molusc_june06.pl", "urb_surface_Link"],
  ["Molusc_june06.pl", "urb_surface/surface"],
  ["Molusc_june06.pl", "urbbase*surface"],
  ["Molusc_june06.pl", "woody_area_0/surface"],
  ["Molusc_june06.pl", "woody_area-removed_woody"],
  ["Molusc_june06.pl", "woody_biofuels_abs_t_1-woody_area_bis"],
  ["Molusc_june06.pl", "woody_max_to_remove-woody_to_remove"],
  ["Molusc_june06.pl", "woody_to_remove/dt('')"],
  ["move1.pl", "(if (x<0;x>100;y<0;y>100)then 1 else 0)", 1],
  ["move1.pl", "(if outside==1 then 3.14/dt(1)else rand(-0.4,0.4)/dt(1))"],
  ["move1.pl", "(if outside==1 then speed*cos(dir+3.14)else speed*cos(dir))"],
  ["move1.pl", "(if outside==1 then speed*sin(dir+3.14)else speed*sin(dir))"],
  ["move1.pl", "3"],
  ["move1.pl", "5"],
  ["move1.pl", "rand(0,6.28)"],
  ["move1.pl", "rand(30,70)"],
  ["nprey_npred.pl", "'E'*element(['Npred'],index(2))"],
  ["nprey_npred.pl", "a*element(['Nprey'],index(1))/(1+sum_haN)"],
  ["nprey_npred.pl", "element([1,2],index(1))"],
  ["nprey_npred.pl", "element([10,20,30],index(1))"],
  ["nprey_npred.pl", "element([100,200,300],index(1))"],
  ["nprey_npred.pl", "element([total_weight_eaten],index(1))"],
  ["nprey_npred.pl", "element(element([[ 0.01, 0.02, 0.03],[ 0.02, 0.04, 0.06]],index(2)),index(1))"],
  ["nprey_npred.pl", "element(element([[ 0.1, 0.2, 0.3],[ 0.2, 0.4, 0.6]],index(2)),index(1))"],
  ["nprey_npred.pl", "element(sum([['E_Npred']]),index(1))"],
  ["nprey_npred.pl", "sum(['E']*[weight])"],
  ["nprey_npred.pl", "sum([h]*[a]*['Nprey'])"],
  ["oom2.pl", "(fmod(index(1),2)== 1.0)"],
  ["oom2.pl", "(if dummy then 0 else centre_x_higher)"],
  ["oom2.pl", "(if dummy then 0 else centre_y_higher)"],
  ["oom2.pl", "(if dummy then 0 else my_level_higher)"],
  ["oom2.pl", "(if index(1)==1 then 0 else int(fmod(index(1)-2,7)))"],
  ["oom2.pl", "(if index(1)==1 then 1 else int((index(1)+5)/7))"],
  ["oom2.pl", "(if posn_in_parent==0 then hi_cx_lower else hi_cx_lower+magic*element(element([[offb]],my_level),int(posn_in_parent)))"],
  ["oom2.pl", "(if posn_in_parent==0 then hi_cy_lower else hi_cy_lower-magic*element(element([[offa]],my_level),int(posn_in_parent)))"],
  ["oom2.pl", "(index(1) is my_parent_lower)"],
  ["oom2.pl", "(index(2)==1)"],
  ["oom2.pl", "(my_level==6)"],
  ["oom2.pl", "[ 0.5, -0.5,-1, -0.5, 0.5,1]"],
  ["oom2.pl", "[ 0.866, 0.866,0, -0.866, -0.866,0]"],
  ["oom2.pl", "50/7^((index(1)-1)/2)"],
  ["oom2.pl", "atan(3*sqrt(3))"],
  ["oom2.pl", "centre_x+element([[offa]],my_level)"],
  ["oom2.pl", "centre_y+element([[offb]],my_level)"],
  ["oom2.pl", "cos(theta)*[offa_even]-sin(theta)*[offb_even]"],
  ["oom2.pl", "hi_level_lower+1"],
  ["oom2.pl", "index(1)"],
  ["oom2.pl", "side*(if even_level then [offa_even] else [offa_odd])"],
  ["oom2.pl", "side*(if even_level then [offb_even] else [offb_odd])"],
  ["oom2.pl", "sin(theta)*[offa_even]+cos(theta)*[offb_even]"],
  ["oom2.pl", "sqrt(3)"],
  ["p025.pl", " 0.07"],
  ["p025.pl", "10"],
  ["p025.pl", "growth_rate*population"],
  ["p028.pl", " 0.1"],
  ["p028.pl", " 0.2"],
  ["p028.pl", " 0.5"],
  ["p028.pl", "20"],
  ["p028.pl", "30"],
  ["p028.pl", "50"],
  ["p028.pl", "aging_rate*mature"],
  ["p028.pl", "births_per_mature_female_per_year*mature_females"],
  ["p028.pl", "death_rate*elderly"],
  ["p028.pl", "female_fraction*mature"],
  ["p028.pl", "maturation_rate*young"],
  ["p038.pl", " 0.667"],
  ["p038.pl", " 3.75"],
  ["p038.pl", " 33.6"],
  ["p038.pl", " 47.6"],
  ["p038.pl", "100"],
  ["p038.pl", "150"],
  ["p038.pl", "2228"],
  ["p038.pl", "39"],
  ["p038.pl", "sierra_gauged_runoff-exports"],
  ["p038.pl", "surface_area*evaporation_rate"],
  ["p038.pl", "surface_area*precipitation_rate"],
  ["p040.pl", " 0.667"],
  ["p040.pl", " 3.75"],
  ["p040.pl", " 33.6"],
  ["p040.pl", " 47.6"],
  ["p040.pl", "100"],
  ["p040.pl", "150"],
  ["p040.pl", "2228"],
  ["p040.pl", "graph(water_in_lake)"],
  ["p040.pl", "sierra_gauged_runoff-exports"],
  ["p040.pl", "surface_area*evaporation_rate"],
  ["p040.pl", "surface_area*precipitation_rate"],
  ["p042.pl", " 0.667"],
  ["p042.pl", " 1.3"],
  ["p042.pl", " 1.359"],
  ["p042.pl", " 1.6"],
  ["p042.pl", " 3.75 *evaporation_rate_multiplier_from_specific_gravity"],
  ["p042.pl", " 7.3"],
  ["p042.pl", "(water_in_lake*mass_of_fresh_water+total_dissolved_solids)/(water_in_lake*mass_of_fresh_water)"],
  ["p042.pl", "100"],
  ["p042.pl", "12"],
  ["p042.pl", "13"],
  ["p042.pl", "150"],
  ["p042.pl", "17"],
  ["p042.pl", "20"],
  ["p042.pl", "2228"],
  ["p042.pl", "230"],
  ["p042.pl", "9"],
  ["p042.pl", "evapotranspiration+exposed_lake_bottom_evaporation+net_grant_lake_evaporation+ground_water_export"],
  ["p042.pl", "graph(specific_gravity)"],
  ["p042.pl", "graph(water_in_lake)"],
  ["p042.pl", "sierra_gauged_runoff-exports"],
  ["p042.pl", "surface_area*evaporation_rate"],
  ["p042.pl", "surface_area*precipitation_rate"],
  ["p042.pl", "ungauged_sierra_runoff+non_sierra_runoff+land_surface_precipitation+diversion_inflows"],
  ["p058.pl", " 0.2"],
  ["p058.pl", "1"],
  ["p058.pl", "10"],
  ["p058.pl", "1000"],
  ["p058.pl", "area_of_flowers*actual_growth_rate"],
  ["p058.pl", "area_of_flowers*decay_rate"],
  ["p058.pl", "area_of_flowers/suitable_area"],
  ["p058.pl", "graph(fraction_occupied)"],
  ["p058.pl", "intrinsic_growth_rate*growth_rate_multiplier"],
  ["p062.pl", " 0.2"],
  ["p062.pl", "'Azero'*exp(r*time(1))/(1+'Azero'*(exp(r*time(1))-1)/'K')"],
  ["p062.pl", "[area_of_flowers,'A_of_t']"],
  ["p062.pl", "1"],
  ["p062.pl", "10"],
  ["p062.pl", "1000"],
  ["p062.pl", "800"],
  ["p062.pl", "area_of_flowers*actual_growth_rate"],
  ["p062.pl", "area_of_flowers*decay_rate"],
  ["p062.pl", "area_of_flowers/suitable_area"],
  ["p062.pl", "graph(fraction_occupied)"],
  ["p062.pl", "intrinsic_growth_rate-decay_rate"],
  ["p062.pl", "intrinsic_growth_rate*growth_rate_multiplier"],
  ["p064.pl", " 0.2"],
  ["p064.pl", " 0.5"],
  ["p064.pl", "1"],
  ["p064.pl", "100"],
  ["p064.pl", "25000"],
  ["p064.pl", "50"],
  ["p064.pl", "fraction_to_sales*annual_revenue_in_millions"],
  ["p064.pl", "graph(size_of_sales_force)"],
  ["p064.pl", "hiring_fraction*(budgeted_size_of_sales_force-size_of_sales_force)"],
  ["p064.pl", "sales_dept_budget*1000000/average_salary"],
  ["p064.pl", "size_of_sales_force*effectiveness_in_widgets_per_day*365"],
  ["p064.pl", "size_of_sales_force*exit_rate"],
  ["p064.pl", "widget_sales*widget_price/1000000"],
  ["predator_prey32.pl", " 0.02"],
  ["predator_prey32.pl", " 0.06"],
  ["predator_prey32.pl", " 0.2"],
  ["predator_prey32.pl", " 0.9"],
  ["predator_prey32.pl", "10"],
  ["predator_prey32.pl", "1000"],
  ["predator_prey32.pl", "5"],
  ["predator_prey32.pl", "50"],
  ["predator_prey32.pl", "g*y*(a*x*x/(x*x+'L'))-m*y"],
  ["predator_prey32.pl", "r*x*(1-x/'K')-a*x*x/(x*x+'L')*y"],
  ["prime.pl", "(fmod(prime_0,quotient)==0)"],
  ["prime.pl", "(found_divisor or quotient>check_limit)"],
  ["prime.pl", "(if done_checks then 0 else prev(0)+1)"],
  ["prime.pl", "(if found_prime then start_prime else prev(0)+2)"],
  ["prime.pl", "(if index(1)==1 then 5 else element([all_primes],index(1)-1)+2)"],
  ["prime.pl", "(if which==0 then 3 else element([all_primes],which))"],
  ["prime.pl", "[prime]"],
  ["prime.pl", "3"],
  ["prime.pl", "95"],
  ["prime.pl", "makearray(element([all_primes],499990+place_in(1)),10)"],
  ["prime.pl", "not found_divisor"],
  ["prime.pl", "sqrt(prime_0)"],
  ["ranking1.pl", "(attribute_role1>attribute_role2)"],
  ["ranking1.pl", "1"],
  ["ranking1.pl", "10"],
  ["ranking1.pl", "count({one_role2})+1"],
  ["ranking1.pl", "rand_const(0,100)"],
  ["respirationQ10.pl", " 2.0"],
  ["respirationQ10.pl", "'Rref'*'Q10'^(('T'-'Tref')/10)"],
  ["respirationQ10.pl", "(if time('')>50 then 40 else time('')-10)"],
  ["respirationQ10.pl", "0"],
  ["respirationQ10.pl", "1"],
  ["SolarRadiationDNDCP.pl", " - (tan(decl)*tan(lat))"],
  ["SolarRadiationDNDCP.pl", " 0.398 *sin( 4.869+ 0.0172 *'Jday'+ 0.0334 *sin( 6.224+ 0.0172 *'Jday'))"],
  ["SolarRadiationDNDCP.pl", " 0.48"],
  ["SolarRadiationDNDCP.pl", " 1.0 - 0.0167 *cos( 0.0172*('Jday'-3))"],
  ["SolarRadiationDNDCP.pl", " 1367.0"],
  ["SolarRadiationDNDCP.pl", "'DayPAR'/('Day_Hrs'* 0.0036)"],
  ["SolarRadiationDNDCP.pl", "('TA'=abs(z2),if'TA'< 0.7 then  1.571-atan('TA'/(1-'TA'^2)^ 0.5) else atan((1-'TA'^2)^ 0.5 /'TA'))"],
  ["SolarRadiationDNDCP.pl", "(if abs('Z')< 0.7 then atan('Z'/(1-'Z'^2)^ 0.5) else pi('')/2-atan((1-'Z'^2)^ 0.5 /'Z'))"],
  ["SolarRadiationDNDCP.pl", "(if z2<0 then  3.1416-'AC' else 'AC')"],
  ["SolarRadiationDNDCP.pl", "(if z2>=1 then 0 elseif z2<= -1 then pi('') else acos)"],
  ["SolarRadiationDNDCP.pl", "(l='Latitude'*pi('')/ 180.0,if abs(l* 1.0)>=pi('')/2 then sgn(l* 1.0)*(pi('')/2- 0.01) else l)"],
  ["SolarRadiationDNDCP.pl", "2*('H'*24)/(2* 3.1416)"],
  ["SolarRadiationDNDCP.pl", "54"],
  ["SolarRadiationDNDCP.pl", "isc*(86400/( 3.1416*r*r))*('H'*sin(lat)*sin(decl)+cos(lat)*cos(decl)*sin('H'))"],
  ["SolarRadiationDNDCP.pl", "psolrad*cloud/ 1000000.0"],
  ["SolarRadiationDNDCP.pl", "solrad* 2.05"],
  ["SolarRadiationDNDCP.pl", "time('')"],
  ["test02_1submodel_1.pl", " 0.1"],
  ["test02_1submodel_1.pl", "'Var1'*'Comp1'"],
  ["test02_1submodel_1.pl", "(if time(1)==init_time(1) then '\"false\"' else head '!=' last(head))"],
  ["test02_1submodel_1.pl", "100"],
  ["test02_1submodel_2.pl", " 0.1"],
  ["test02_1submodel_2.pl", "'Var1'*'Comp1'"],
  ["test02_1submodel_2.pl", "(if time(1)==init_time(1) then '\"false\"' else head '!=' last(head))"],
  ["test02_1submodel_2.pl", "100"],
  ["test02_1submodel_3.pl", " 0.1"],
  ["test02_1submodel_3.pl", "'Var1'*'Comp1'"],
  ["test02_1submodel_3.pl", "(if time(1)==init_time(1) then '\"false\"' else head '!=' last(head))"],
  ["test02_1submodel_3.pl", "100"],
  ["TestJarvisStomataMode.pl", " 0.611 *exp( 17.27*'Temperature'/('Temperature'+ 237.15))"],
  ["TestJarvisStomataMode.pl", "'Gs_max'*'Gs_PFD'*'GsVPD'*'GsT'*'GsCO2'"],
  ["TestJarvisStomataMode.pl", "'Gsl'*('PFD'+'Gdark'/'Gsl')/(1+'Gsl'*('PFD'+'Gdark'/'Gsl'))"],
  ["TestJarvisStomataMode.pl", "'PFD'"],
  ["TestJarvisStomataMode.pl", "'SVP'*(1-'RH')"],
  ["TestJarvisStomataMode.pl", "('Tmax'-'Topt')/('Topt'-'Tmin')"],
  ["TestJarvisStomataMode.pl", "(g=('Temperature'-'Tmin')*('Tmax'-'Temperature')^p/(('T0'-'Tmin')*('Tmax'-'T0')^p),min(max(g,0),1))"],
  ["TestJarvisStomataMode.pl", "(g=1-('VPD'-'Dthresh')/('D0'-'Dthresh'),max(min(g, 1.0),0))"],
  ["TestJarvisStomataMode.pl", "(g=1-gsja*('CO2Conc'-averageCO2),max(min(g, 1.0), 0.0))"],
  ["TestJarvisStomataModel_V4_P.pl", "'Gs_max'*'Gs_PFD'*'GsVPD'*'GsT'*'GsCO2'"],
  ["TestJarvisStomataModel_V4_P.pl", "'Gsl'*('PFD'+'Gdark'/'Gsl')/(1+'Gsl'*('PFD'+'Gdark'/'Gsl'))"],
  ["TestJarvisStomataModel_V4_P.pl", "'PFD'"],
  ["TestJarvisStomataModel_V4_P.pl", "'SVP'*(1-'RH')"],
  ["TestJarvisStomataModel_V4_P.pl", "('Tmax'-'Topt')/('Topt'-'Tmin')"],
  ["TestJarvisStomataModel_V4_P.pl", "(g=('Temperature'-'Tmin')*('Tmax'-'Temperature')^p/(('T0'-'Tmin')*('Tmax'-'T0')^p),min(max(g,0),1))"],
  ["TestJarvisStomataModel_V4_P.pl", "(g=1-('VPD'-'Dthresh')/('D0'-'Dthresh'),max(min(g,1.0),0))"],
  ["TestJarvisStomataModel_V4_P.pl", "(g=1-gsja*('CO2Conc'-averageCO2),max(min(g,1.0),0.0))"],
  ["TestJarvisStomataModel_V4_P.pl", "0.611*exp(17.27*'Temperature'/('Temperature'+237.15))"],
  ["Thornthwaite.pl", " 0.49 + 0.0179 *'I'- 7.71 *10^ -5*'I'^2+ 6.75 *10^ -7*'I'^3"],
  ["Thornthwaite.pl", "(if'Ta'<=0 then 0 else dl*16*(10*'Ta'/'I')^a)"],
  ["Thornthwaite.pl", "(if'Ta'>0 then ('Ta'/5)^ 1.5 else 0)"],
  ["Thornthwaite.pl", "element(['Ta'],month)"],
  ["Thornthwaite.pl", "element([dl],month)"],
  ["Thornthwaite.pl", "sum([i])"],
  ["Thornthwaite.pl", "time('')+1"],
  ["vegproportions1.pl", "(if time(1)==0 then [ 0.25, 0.1, 0.65, 0.0] else last([new_proportions]))"],
  ["vegproportions1.pl", "(if time(1)==0 then [ 0.25, 0.1, 0.65, 0.0] else sum([[transition_probabilities]]*prev(1)))"],
  ["vegproportions1.pl", "[[ 0.3, 0.5, 0.2, 0.0],[ 0.0, 0.4, 0.6, 0.0],[ 0.0, 0.0, 0.7, 0.3],[ 0.7, 0.0, 0.0, 0.3]]"],
  ["vegproportions1.pl", "sum([[transition_probabilities]]*[current_proportions])"]
];
